/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering Procedure [dbo].[rptGetDailyHeadWiseDemandCollection]...';


GO

ALTER PROCEDURE [dbo].[rptGetDailyHeadWiseDemandCollection] 
	@StartDate int, @EndDate int
	
AS
DECLARE @s SMALLDATETIME, @e SMALLDATETIME;
set @s=@StartDate

set @e=@EndDate

begin

	set nocount on;

	select ROW_NUMBER() over(order by(select 1)) as sl,CONVERT(varchar,l.paymentDate,103) as PaymentDate, t.taxName as TaxName, l.totalAmount as TotalAmount, l.penaltyAmount as PenaltyAmount, CONVERT(varchar,@s,103) as StartDate, CONVERT(varchar,@e,103)  as EndDate
	
	from tblLedger as l
	inner join tblDemand as d on l.demandId = d.demandId
	inner join mstTaxMaster as t on l.taxId = t.taxId
	where d.isPaymentMade = 1 and 
	cast(convert(varchar,l.paymentDate,103) as int) >= @StartDate and 
	cast(convert(varchar,l.paymentDate,103) as int) <= @EndDate

end
GO
PRINT N'Altering Procedure [dbo].[rptMinorHeadWiseCollectionbytofromdate]...';


GO

ALTER PROCEDURE [dbo].[rptMinorHeadWiseCollectionbytofromdate] 
	@StartDate int, @EndDate int
	
AS
--DECLARE @s SMALLDATETIME, @e SMALLDATETIME;
--set @s=@StartDate

--set @e=@EndDate

begin

	set nocount on;
	 
	Select ROW_NUMBER() over(order by(select 1)) as Sl,
	m.minorHeadName as MinorHeadName
	,sum(de.totalAmount) as TotalAmount
	from mstMinorHead m
    inner join mstDetailHead as d on m.minorHeadId = d.minorHeadId
    inner join mstTaxMaster as t on d.detailHeadId = t.detailHeadId
    inner join tblDemand as de on t.taxId = de.taxId
	where de.isPaymentMade = 1  
	--and l.paymentDate between @s and @e
	and cast(convert(varchar,de.paymentDate,103) as int) >= @StartDate
	
	 and cast(convert(varchar,de.paymentDate,103) as int) <=  @EndDate
	 group by m.minorHeadId, m.minorHeadName
	 
	
end
GO
PRINT N'Update complete.';


GO
