CREATE TABLE [enumOwnerType](
	[ownerTypeId] [int] IDENTITY(1,1) NOT NULL,
	[ownerType] [varchar](100) NOT NULL,
 CONSTRAINT [PK_enumOwnertype_ownerTypeId] PRIMARY KEY CLUSTERED 
(
	[OwnerTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
