/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key 08c4d738-9a10-4e78-90c6-2bb88d161c79 is skipped, element [dbo].[trnConstructionApprovalApplicationFeeDetail].[Id] (SqlSimpleColumn) will not be renamed to constructionApprovalApplicationFeeId';


GO
PRINT N'Rename refactoring operation with key 8ad45e7f-702b-4eb6-a7c6-becaa1171ee6 is skipped, element [dbo].[trnConstructionApprovalApplicationFeeDetail].[cid] (SqlSimpleColumn) will not be renamed to ttin';


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '08c4d738-9a10-4e78-90c6-2bb88d161c79')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('08c4d738-9a10-4e78-90c6-2bb88d161c79')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '8ad45e7f-702b-4eb6-a7c6-becaa1171ee6')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('8ad45e7f-702b-4eb6-a7c6-becaa1171ee6')

GO

GO
PRINT N'Update complete.';


GO
