/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [dbo].[trnLandDetail].[propertyTypeId] on table [dbo].[trnLandDetail] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [dbo].[trnLandDetail])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping [dbo].[FK_trnLandDetail_ToTable]...';


GO
ALTER TABLE [dbo].[trnLandDetail] DROP CONSTRAINT [FK_trnLandDetail_ToTable];


GO
PRINT N'Dropping [dbo].[FK_trnLandDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[trnLandDetail] DROP CONSTRAINT [FK_trnLandDetail_ToTable_4];


GO
PRINT N'Dropping [dbo].[FK_trnLandDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[trnLandDetail] DROP CONSTRAINT [FK_trnLandDetail_ToTable_1];


GO
PRINT N'Dropping [dbo].[FK_trnLandDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[trnLandDetail] DROP CONSTRAINT [FK_trnLandDetail_ToTable_2];


GO
PRINT N'Dropping [dbo].[FK_trnLandDetail_ToTable_5]...';


GO
ALTER TABLE [dbo].[trnLandDetail] DROP CONSTRAINT [FK_trnLandDetail_ToTable_5];


GO
PRINT N'Dropping [dbo].[FK_trnLandDetail_ToTable_6]...';


GO
ALTER TABLE [dbo].[trnLandDetail] DROP CONSTRAINT [FK_trnLandDetail_ToTable_6];


GO
PRINT N'Dropping [dbo].[FK_trnLandDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[trnLandDetail] DROP CONSTRAINT [FK_trnLandDetail_ToTable_3];


GO
PRINT N'Starting rebuilding table [dbo].[trnLandDetail]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_trnLandDetail] (
    [trnFTLandDetailId]       INT             IDENTITY (1, 1) NOT NULL,
    [transactorTypeId]        INT             NOT NULL,
    [landTransferTypeId]      INT             NOT NULL,
    [lapId]                   INT             NOT NULL,
    [demkhongId]              INT             NOT NULL,
    [streetNameId]            INT             NOT NULL,
    [landTypeId]              INT             NOT NULL,
    [landUseSubCategoryId]    INT             NOT NULL,
    [propertyTypeId]          INT             NOT NULL,
    [plotNo]                  VARCHAR (145)   NOT NULL,
    [landAcerage]             DECIMAL (10, 2) NOT NULL,
    [landValue]               DECIMAL (10, 2) NOT NULL,
    [landPoolingRate]         DECIMAL (10, 3) NOT NULL,
    [structureAvailable]      BIT             NOT NULL,
    [plotAddress]             VARCHAR (255)   NOT NULL,
    [location]                VARCHAR (255)   NULL,
    [IsApproved]              BIT             NOT NULL,
    [createdBy]               INT             NOT NULL,
    [creationOn]              DATE            NOT NULL,
    [modifiedBy]              INT             NULL,
    [modifiedOn]              DATETIME        NULL,
    [vacantLandTaxApplicable] BIT             NULL,
    [garbageApplicable]       BIT             NULL,
    [streetLightApplicable]   BIT             NULL,
    [eSakorTransactionId]     VARCHAR (250)   NOT NULL,
    PRIMARY KEY CLUSTERED ([trnFTLandDetailId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[trnLandDetail])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_trnLandDetail] ON;
        INSERT INTO [dbo].[tmp_ms_xx_trnLandDetail] ([trnFTLandDetailId], [transactorTypeId], [landTransferTypeId], [lapId], [demkhongId], [streetNameId], [landTypeId], [landUseSubCategoryId], [plotNo], [landAcerage], [landValue], [landPoolingRate], [structureAvailable], [plotAddress], [location], [IsApproved], [createdBy], [creationOn], [modifiedBy], [modifiedOn], [vacantLandTaxApplicable], [garbageApplicable], [streetLightApplicable], [eSakorTransactionId])
        SELECT   [trnFTLandDetailId],
                 [transactorTypeId],
                 [landTransferTypeId],
                 [lapId],
                 [demkhongId],
                 [streetNameId],
                 [landTypeId],
                 [landUseSubCategoryId],
                 [plotNo],
                 [landAcerage],
                 [landValue],
                 [landPoolingRate],
                 [structureAvailable],
                 [plotAddress],
                 [location],
                 [IsApproved],
                 [createdBy],
                 [creationOn],
                 [modifiedBy],
                 [modifiedOn],
                 [vacantLandTaxApplicable],
                 [garbageApplicable],
                 [streetLightApplicable],
                 [eSakorTransactionId]
        FROM     [dbo].[trnLandDetail]
        ORDER BY [trnFTLandDetailId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_trnLandDetail] OFF;
    END

DROP TABLE [dbo].[trnLandDetail];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_trnLandDetail]', N'trnLandDetail';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[FK_trnLandDetail_ToTable]...';


GO
ALTER TABLE [dbo].[trnLandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandDetail_ToTable] FOREIGN KEY ([lapId]) REFERENCES [dbo].[mstLap] ([lapId]);


GO
PRINT N'Creating [dbo].[FK_trnLandDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[trnLandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandDetail_ToTable_4] FOREIGN KEY ([demkhongId]) REFERENCES [dbo].[mstDemkhong] ([demkhongId]);


GO
PRINT N'Creating [dbo].[FK_trnLandDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[trnLandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandDetail_ToTable_1] FOREIGN KEY ([landUseSubCategoryId]) REFERENCES [dbo].[mstLandUseSubCategory] ([landUseSubCategoryId]);


GO
PRINT N'Creating [dbo].[FK_trnLandDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[trnLandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandDetail_ToTable_2] FOREIGN KEY ([landTypeId]) REFERENCES [dbo].[mstLandType] ([landTypeId]);


GO
PRINT N'Creating [dbo].[FK_trnLandDetail_ToTable_5]...';


GO
ALTER TABLE [dbo].[trnLandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandDetail_ToTable_5] FOREIGN KEY ([streetNameId]) REFERENCES [dbo].[mstStreetName] ([streetNameId]);


GO
PRINT N'Creating [dbo].[FK_trnLandDetail_ToTable_6]...';


GO
ALTER TABLE [dbo].[trnLandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandDetail_ToTable_6] FOREIGN KEY ([transactorTypeId]) REFERENCES [dbo].[enumTransactorType] ([transactorTypeId]);


GO
PRINT N'Creating [dbo].[FK_trnLandDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[trnLandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandDetail_ToTable_3] FOREIGN KEY ([landTransferTypeId]) REFERENCES [dbo].[enumLandTransferType] ([landTransferTypeId]);


GO
PRINT N'Creating [dbo].[FK_trnLandDetail_ToTable_7]...';


GO
ALTER TABLE [dbo].[trnLandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandDetail_ToTable_7] FOREIGN KEY ([propertyTypeId]) REFERENCES [dbo].[enumPropertyType] ([propertyTypeId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[trnLandDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandDetail_ToTable];

ALTER TABLE [dbo].[trnLandDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandDetail_ToTable_4];

ALTER TABLE [dbo].[trnLandDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandDetail_ToTable_1];

ALTER TABLE [dbo].[trnLandDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandDetail_ToTable_2];

ALTER TABLE [dbo].[trnLandDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandDetail_ToTable_5];

ALTER TABLE [dbo].[trnLandDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandDetail_ToTable_6];

ALTER TABLE [dbo].[trnLandDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandDetail_ToTable_3];

ALTER TABLE [dbo].[trnLandDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandDetail_ToTable_7];


GO
PRINT N'Update complete.';


GO
