/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.REVENUE\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.REVENUE\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [dbo].[trnSewerageConnection].[cid] is being dropped, data loss could occur.

The column [dbo].[trnSewerageConnection].[emailId] is being dropped, data loss could occur.

The column [dbo].[trnSewerageConnection].[name] is being dropped, data loss could occur.

The column [dbo].[trnSewerageConnection].[ownerName] is being dropped, data loss could occur.

The column [dbo].[trnSewerageConnection].[plotNo] is being dropped, data loss could occur.

The column [dbo].[trnSewerageConnection].[thramNo] is being dropped, data loss could occur.

The column [dbo].[trnSewerageConnection].[createdBy] on table [dbo].[trnSewerageConnection] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column [dbo].[trnSewerageConnection].[createdOn] on table [dbo].[trnSewerageConnection] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column [dbo].[trnSewerageConnection].[landOwnershipId] on table [dbo].[trnSewerageConnection] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [dbo].[trnSewerageConnection])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Rename refactoring operation with key 58c104bb-860a-404b-89f1-60df1f2c91f3 is skipped, element [dbo].[trnSewerageConnection].[taxPayerId] (SqlSimpleColumn) will not be renamed to land';


GO
PRINT N'Dropping Foreign Key [dbo].[FK_trnSewerageConnection_ToTable]...';


GO
ALTER TABLE [dbo].[trnSewerageConnection] DROP CONSTRAINT [FK_trnSewerageConnection_ToTable];


GO
PRINT N'Starting rebuilding table [dbo].[trnSewerageConnection]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_trnSewerageConnection] (
    [sewerageConnectionId] INT             IDENTITY (1, 1) NOT NULL,
    [transactionId]        BIGINT          NOT NULL,
    [amount]               DECIMAL (18, 2) NOT NULL,
    [mobileNo]             VARCHAR (50)    NOT NULL,
    [contactAddress]       VARCHAR (300)   NOT NULL,
    [landOwnershipId]      INT             NOT NULL,
    [g2cApplicationNo]     VARCHAR (300)   NOT NULL,
    [createdBy]            INT             NOT NULL,
    [createdOn]            DATETIME        NOT NULL,
    [modifiedBy]           INT             NULL,
    [modifiedOn]           DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([sewerageConnectionId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[trnSewerageConnection])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_trnSewerageConnection] ON;
        INSERT INTO [dbo].[tmp_ms_xx_trnSewerageConnection] ([sewerageConnectionId], [transactionId], [amount], [g2cApplicationNo], [mobileNo], [contactAddress])
        SELECT   [sewerageConnectionId],
                 [transactionId],
                 [amount],
                 [g2cApplicationNo],
                 [mobileNo],
                 [contactAddress]
        FROM     [dbo].[trnSewerageConnection]
        ORDER BY [sewerageConnectionId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_trnSewerageConnection] OFF;
    END

DROP TABLE [dbo].[trnSewerageConnection];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_trnSewerageConnection]', N'trnSewerageConnection';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnSewerageConnection_ToTable]...';


GO
ALTER TABLE [dbo].[trnSewerageConnection] WITH NOCHECK
    ADD CONSTRAINT [FK_trnSewerageConnection_ToTable] FOREIGN KEY ([transactionId]) REFERENCES [dbo].[tblTransactionDetail] ([transactionId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnSewerageConnection_ToTable_1]...';


GO
ALTER TABLE [dbo].[trnSewerageConnection] WITH NOCHECK
    ADD CONSTRAINT [FK_trnSewerageConnection_ToTable_1] FOREIGN KEY ([landOwnershipId]) REFERENCES [dbo].[tblLandOwnershipDetail] ([landOwnershipId]);


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '58c104bb-860a-404b-89f1-60df1f2c91f3')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('58c104bb-860a-404b-89f1-60df1f2c91f3')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[trnSewerageConnection] WITH CHECK CHECK CONSTRAINT [FK_trnSewerageConnection_ToTable];

ALTER TABLE [dbo].[trnSewerageConnection] WITH CHECK CHECK CONSTRAINT [FK_trnSewerageConnection_ToTable_1];


GO
PRINT N'Update complete.';


GO
