/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [dbo].[tblLedger].[receiptId] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[tblLedger])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The column [dbo].[tblPaymentLeger].[receiptYear] on table [dbo].[tblPaymentLeger] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column [dbo].[tblPaymentLeger].[slNo] on table [dbo].[tblPaymentLeger] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column amount on table [dbo].[tblPaymentLeger] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column paymentModeId on table [dbo].[tblPaymentLeger] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The type for column paymentModeId in table [dbo].[tblPaymentLeger] is currently  NCHAR (10) NULL but is being changed to  INT NOT NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  INT NOT NULL.

The type for column paymentModeNo in table [dbo].[tblPaymentLeger] is currently  NCHAR (10) NULL but is being changed to  VARCHAR (250) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  VARCHAR (250) NULL.
*/

IF EXISTS (select top 1 1 from [dbo].[tblPaymentLeger])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'The following operation was generated from a refactoring log file 420b6afc-4390-4991-8e25-5a93633801e1';

PRINT N'Rename [dbo].[tblPaymentLeger].[receiptId] to receiptNo';


GO
EXECUTE sp_rename @objname = N'[dbo].[tblPaymentLeger].[receiptId]', @newname = N'receiptNo', @objtype = N'COLUMN';


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_0]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_0];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_1];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_2];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_3]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_3];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_4]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_4];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_5]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_5];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_6]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_6];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_7]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_7];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_8]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_8];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_9]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_9];


GO
PRINT N'Dropping [dbo].[FK_tblLedger_ToTable_10]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_10];


GO
PRINT N'Starting rebuilding table [dbo].[tblLedger]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tblLedger] (
    [ledgerId]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [demandId]                BIGINT          NOT NULL,
    [transactionId]           BIGINT          NOT NULL,
    [taxId]                   INT             NOT NULL,
    [financialYearId]         INT             NOT NULL,
    [calendarYearId]          INT             NOT NULL,
    [landDetailId]            INT             NULL,
    [taxPayerId]              INT             NULL,
    [totalAmount]             DECIMAL (18, 2) NOT NULL,
    [paymentDate]             DATETIME        NOT NULL,
    [receiptNo]               VARCHAR (350)   NULL,
    [reconciledOn]            DATETIME        NULL,
    [createdBy]               INT             NOT NULL,
    [createdOn]               DATETIME        NOT NULL,
    [modifiedBy]              INT             NULL,
    [modifiedOn]              DATETIME        NULL,
    [applicantId]             INT             NULL,
    [ecRenewalId]             INT             NULL,
    [landLeaseDemandDetailId] BIGINT          NULL,
    [parkingDemandDetailId]   BIGINT          NULL,
    [stallDemandDetailId]     BIGINT          NULL,
    [houseRentDemandDetailId] BIGINT          NULL,
    [miscellaneousRecordId]   BIGINT          NULL,
    PRIMARY KEY CLUSTERED ([ledgerId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tblLedger])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblLedger] ON;
        INSERT INTO [dbo].[tmp_ms_xx_tblLedger] ([ledgerId], [demandId], [transactionId], [taxId], [financialYearId], [calendarYearId], [landDetailId], [taxPayerId], [totalAmount], [paymentDate], [reconciledOn], [createdBy], [createdOn], [modifiedBy], [modifiedOn], [applicantId], [ecRenewalId], [landLeaseDemandDetailId], [parkingDemandDetailId], [stallDemandDetailId], [houseRentDemandDetailId], [miscellaneousRecordId])
        SELECT   [ledgerId],
                 [demandId],
                 [transactionId],
                 [taxId],
                 [financialYearId],
                 [calendarYearId],
                 [landDetailId],
                 [taxPayerId],
                 [totalAmount],
                 [paymentDate],
                 [reconciledOn],
                 [createdBy],
                 [createdOn],
                 [modifiedBy],
                 [modifiedOn],
                 [applicantId],
                 [ecRenewalId],
                 [landLeaseDemandDetailId],
                 [parkingDemandDetailId],
                 [stallDemandDetailId],
                 [houseRentDemandDetailId],
                 [miscellaneousRecordId]
        FROM     [dbo].[tblLedger]
        ORDER BY [ledgerId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblLedger] OFF;
    END

DROP TABLE [dbo].[tblLedger];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tblLedger]', N'tblLedger';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tblPaymentLeger]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tblPaymentLeger] (
    [paymentLedgerId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [transactionId]   BIGINT          NOT NULL,
    [paymentModeId]   INT             NOT NULL,
    [amount]          DECIMAL (18, 2) NOT NULL,
    [paymentModeNo]   VARCHAR (250)   NULL,
    [paymentModeDate] DATE            NULL,
    [receiptNo]       VARCHAR (350)   NULL,
    [slNo]            INT             NOT NULL,
    [receiptYear]     INT             NOT NULL,
    [createdBy]       INT             NOT NULL,
    [createdOn]       DATETIME        NOT NULL,
    [modifiedBy]      INT             NULL,
    [modifiedOn]      DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([paymentLedgerId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tblPaymentLeger])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblPaymentLeger] ON;
        INSERT INTO [dbo].[tmp_ms_xx_tblPaymentLeger] ([paymentLedgerId], [transactionId], [amount], [receiptNo], [paymentModeId], [paymentModeNo], [paymentModeDate], [createdBy], [createdOn], [modifiedBy], [modifiedOn])
        SELECT   [paymentLedgerId],
                 [transactionId],
                 [amount],
                 [receiptNo],
                 [paymentModeId],
                 [paymentModeNo],
                 [paymentModeDate],
                 [createdBy],
                 [createdOn],
                 [modifiedBy],
                 [modifiedOn]
        FROM     [dbo].[tblPaymentLeger]
        ORDER BY [paymentLedgerId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblPaymentLeger] OFF;
    END

DROP TABLE [dbo].[tblPaymentLeger];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tblPaymentLeger]', N'tblPaymentLeger';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable] FOREIGN KEY ([demandId]) REFERENCES [dbo].[tblDemand] ([demandId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_0]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_0] FOREIGN KEY ([taxId]) REFERENCES [dbo].[mstTaxMaster] ([taxId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_1] FOREIGN KEY ([applicantId]) REFERENCES [dbo].[mstECApplicantdetail] ([applicantId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_2] FOREIGN KEY ([ecRenewalId]) REFERENCES [dbo].[tblECRenewalDetail] ([ecRenewalId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_3]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_3] FOREIGN KEY ([landLeaseDemandDetailId]) REFERENCES [dbo].[tblLandLeaseDemandDetail] ([landLeaseDemandDetailId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_4]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_4] FOREIGN KEY ([parkingDemandDetailId]) REFERENCES [dbo].[tblParkingFeeDemandDetail] ([parkingDemandDetailId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_5]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_5] FOREIGN KEY ([stallDemandDetailId]) REFERENCES [dbo].[tblStallDetailDemand] ([stallDemandDetailId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_6]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_6] FOREIGN KEY ([houseRentDemandDetailId]) REFERENCES [dbo].[tblHouseRentDemandDetail] ([houseRentDemandDetailId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_7]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_7] FOREIGN KEY ([financialYearId]) REFERENCES [dbo].[mstFinancialYear] ([financialYearId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_8]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_8] FOREIGN KEY ([calendarYearId]) REFERENCES [dbo].[mstCalendarYear] ([calendarYearId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_9]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_9] FOREIGN KEY ([miscellaneousRecordId]) REFERENCES [dbo].[tblMiscellaneousRecord] ([miscellaneousRecordId]);


GO
PRINT N'Creating [dbo].[FK_tblLedger_ToTable_10]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_10] FOREIGN KEY ([transactionId]) REFERENCES [dbo].[tblTransactionDetail] ([transactionId]);


GO
PRINT N'Creating [dbo].[FK_tblPaymentLeger_ToTable]...';


GO
ALTER TABLE [dbo].[tblPaymentLeger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblPaymentLeger_ToTable] FOREIGN KEY ([transactionId]) REFERENCES [dbo].[tblTransactionDetail] ([transactionId]);


GO
PRINT N'Creating [dbo].[FK_tblPaymentLeger_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblPaymentLeger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblPaymentLeger_ToTable_1] FOREIGN KEY ([paymentModeId]) REFERENCES [dbo].[enumPaymentMode] ([paymentModeId]);


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '420b6afc-4390-4991-8e25-5a93633801e1')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('420b6afc-4390-4991-8e25-5a93633801e1')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_0];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_1];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_2];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_3];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_4];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_5];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_6];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_7];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_8];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_9];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_10];

ALTER TABLE [dbo].[tblPaymentLeger] WITH CHECK CHECK CONSTRAINT [FK_tblPaymentLeger_ToTable];

ALTER TABLE [dbo].[tblPaymentLeger] WITH CHECK CHECK CONSTRAINT [FK_tblPaymentLeger_ToTable_1];


GO
PRINT N'Update complete.';


GO
