/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__7DCDAAA2];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__yearO__7EC1CEDB];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__7FB5F314];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__2022C2A6];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__79FD19BE];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__7AF13DF7];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__garba__7BE56230];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__stree__7CD98669];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__1F2E9E6D];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__trans__1E3A7A34];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__1D4655FB];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__1C5231C2];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__mater__075714DC];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__archF__084B3915];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__roofi__093F5D4E];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__roofi__0A338187];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__tradi__0B27A5C0];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__00AA174D];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__payme__019E3B86];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__water__02925FBF];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__sewer__038683F8];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__attic__047AA831];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__struc__056ECC6A];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__struc__0662F0A3];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__0C1BC9F9];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__bound__0D0FEE32];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__plant__0E04126B];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__water__0EF836A4];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__numbe__0FEC5ADD];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__parki__10E07F16];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__fireE__11D4A34F];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__water__12C8C788];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__roadA__13BCEBC1];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__drain__14B10FFA];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__dateO__15A53433];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__1699586C];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__178D7CA5];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__1881A0DE];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__advan__1975C517];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__advan__1A69E950];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__remar__1B5E0D89];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingUnitDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_3];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_1];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_2];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_4];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_5]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_5];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_6]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_6];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_7]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_7];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_8]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_8];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_9]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_9];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_10]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_10];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_11]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_11];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingDetail_ToTable_12]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_12];


GO
PRINT N'Starting rebuilding table [dbo].[mstBuildingDetail]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_mstBuildingDetail] (
    [buildingDetailId]              INT             IDENTITY (1, 1) NOT NULL,
    [landDetailId]                  INT             NOT NULL,
    [buildingClassId]               INT             DEFAULT '1' NOT NULL,
    [floorTypeId]                   INT             DEFAULT 1 NOT NULL,
    [buildingNo]                    VARCHAR (250)   DEFAULT NULL NULL,
    [buildupArea]                   DECIMAL (10, 2) NOT NULL,
    [plinthArea]                    DECIMAL (18, 2) NULL,
    [noOfUnits]                     INT             NOT NULL,
    [numberOfFloors]                INT             NOT NULL,
    [garbagServiceAccessibilityId]  INT             DEFAULT NULL NULL,
    [streetLightAccessibilityId]    INT             DEFAULT NULL NULL,
    [occupancyCertificateNo]        VARCHAR (256)   DEFAULT NULL NULL,
    [constructionTypeId]            INT             NOT NULL,
    [yearOfConstruction]            INT             DEFAULT NULL NULL,
    [occupancyCertificateIssued]    BIT             DEFAULT NULL NULL,
    [occupancyCertificateIssueDate] DATE            DEFAULT NULL NULL,
    [paymentCompletionStatusId]     BIT             DEFAULT '0' NOT NULL,
    [waterConnection]               BIT             DEFAULT NULL NULL,
    [sewerageConnection]            BIT             DEFAULT NULL NULL,
    [attic]                         BIT             DEFAULT NULL NULL,
    [structureCategoryId]           INT             DEFAULT NULL NULL,
    [structureTypeId]               INT             DEFAULT NULL NULL,
    [materialTypeId]                INT             DEFAULT NULL NULL,
    [archFeature]                   BIT             DEFAULT NULL NULL,
    [roofing]                       BIT             DEFAULT NULL NULL,
    [roofingTypeId]                 INT             DEFAULT NULL NULL,
    [traditionalPainting]           BIT             DEFAULT NULL NULL,
    [buildingColourId]              INT             DEFAULT NULL NULL,
    [boundaryTypeId]                INT             DEFAULT NULL NULL,
    [plantation]                    BIT             DEFAULT NULL NULL,
    [waterTankLocationId]           INT             DEFAULT NULL NULL,
    [numberDisplayed]               BIT             DEFAULT NULL NULL,
    [parkingSlotId]                 INT             DEFAULT NULL NULL,
    [fireExtingusher]               BIT             DEFAULT NULL NULL,
    [waterSupplyAccessibilityId]    INT             DEFAULT NULL NULL,
    [roadAccess]                    BIT             DEFAULT NULL NULL,
    [drainToStormWaterDrain]        BIT             DEFAULT NULL NULL,
    [dateOfFinalInspection]         DATE            DEFAULT NULL NULL,
    [occupancyAlteredOn]            DATE            DEFAULT NULL NULL,
    [occupancyAlteredBy]            INT             DEFAULT NULL NULL,
    [occupancyReferenceId]          INT             DEFAULT NULL NULL,
    [advanceInfoFedBy]              INT             DEFAULT NULL NULL,
    [advanceInfoInfoFedOn]          DATE            DEFAULT NULL NULL,
    [remarks]                       VARCHAR (345)   DEFAULT NULL NULL,
    [modificationRemarks]           VARCHAR (300)   DEFAULT NULL NULL,
    [modificationReasonId]          INT             DEFAULT NULL NULL,
    [transactionId]                 INT             DEFAULT NULL NULL,
    [createdBy]                     INT             NOT NULL,
    [createdOn]                     DATETIME        NOT NULL,
    [modifiedBy]                    INT             DEFAULT NULL NULL,
    [modifiedOn]                    DATETIME        DEFAULT NULL NULL,
    PRIMARY KEY CLUSTERED ([buildingDetailId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[mstBuildingDetail])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstBuildingDetail] ON;
        INSERT INTO [dbo].[tmp_ms_xx_mstBuildingDetail] ([buildingDetailId], [landDetailId], [buildingClassId], [buildingNo], [buildupArea], [plinthArea], [noOfUnits], [numberOfFloors], [garbagServiceAccessibilityId], [streetLightAccessibilityId], [occupancyCertificateNo], [constructionTypeId], [yearOfConstruction], [occupancyCertificateIssued], [occupancyCertificateIssueDate], [paymentCompletionStatusId], [waterConnection], [sewerageConnection], [attic], [structureCategoryId], [structureTypeId], [materialTypeId], [archFeature], [roofing], [roofingTypeId], [traditionalPainting], [buildingColourId], [boundaryTypeId], [plantation], [waterTankLocationId], [numberDisplayed], [parkingSlotId], [fireExtingusher], [waterSupplyAccessibilityId], [roadAccess], [drainToStormWaterDrain], [dateOfFinalInspection], [occupancyAlteredOn], [occupancyAlteredBy], [occupancyReferenceId], [advanceInfoFedBy], [advanceInfoInfoFedOn], [remarks], [modificationRemarks], [modificationReasonId], [transactionId], [createdBy], [createdOn], [modifiedBy], [modifiedOn])
        SELECT   [buildingDetailId],
                 [landDetailId],
                 [buildingClassId],
                 [buildingNo],
                 [buildupArea],
                 [plinthArea],
                 [noOfUnits],
                 [numberOfFloors],
                 [garbagServiceAccessibilityId],
                 [streetLightAccessibilityId],
                 [occupancyCertificateNo],
                 [constructionTypeId],
                 [yearOfConstruction],
                 [occupancyCertificateIssued],
                 [occupancyCertificateIssueDate],
                 [paymentCompletionStatusId],
                 [waterConnection],
                 [sewerageConnection],
                 [attic],
                 [structureCategoryId],
                 [structureTypeId],
                 [materialTypeId],
                 [archFeature],
                 [roofing],
                 [roofingTypeId],
                 [traditionalPainting],
                 [buildingColourId],
                 [boundaryTypeId],
                 [plantation],
                 [waterTankLocationId],
                 [numberDisplayed],
                 [parkingSlotId],
                 [fireExtingusher],
                 [waterSupplyAccessibilityId],
                 [roadAccess],
                 [drainToStormWaterDrain],
                 [dateOfFinalInspection],
                 [occupancyAlteredOn],
                 [occupancyAlteredBy],
                 [occupancyReferenceId],
                 [advanceInfoFedBy],
                 [advanceInfoInfoFedOn],
                 [remarks],
                 [modificationRemarks],
                 [modificationReasonId],
                 [transactionId],
                 [createdBy],
                 [createdOn],
                 [modifiedBy],
                 [modifiedOn]
        FROM     [dbo].[mstBuildingDetail]
        ORDER BY [buildingDetailId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstBuildingDetail] OFF;
    END

DROP TABLE [dbo].[mstBuildingDetail];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_mstBuildingDetail]', N'mstBuildingDetail';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[FK_mstBuildingUnitDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable] FOREIGN KEY ([buildingDetailId]) REFERENCES [dbo].[mstBuildingDetail] ([buildingDetailId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_3] FOREIGN KEY ([structureTypeId]) REFERENCES [dbo].[mstStructureType] ([structureTypeId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable] FOREIGN KEY ([landDetailId]) REFERENCES [dbo].[mstLandDetail] ([landDetailId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_1] FOREIGN KEY ([constructionTypeId]) REFERENCES [dbo].[mstConstructionType] ([constructionTypeId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_2] FOREIGN KEY ([structureCategoryId]) REFERENCES [dbo].[mstStructureCategory] ([structureCategoryId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_4] FOREIGN KEY ([materialTypeId]) REFERENCES [dbo].[mstMaterialType] ([materialTypeId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_5]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_5] FOREIGN KEY ([roofingTypeId]) REFERENCES [dbo].[mstRoofingType] ([roofingTypeId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_6]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_6] FOREIGN KEY ([buildingColourId]) REFERENCES [dbo].[mstBuildingColour] ([buildingColourId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_7]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_7] FOREIGN KEY ([boundaryTypeId]) REFERENCES [dbo].[mstBoundaryType] ([boundaryTypeId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_8]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_8] FOREIGN KEY ([waterTankLocationId]) REFERENCES [dbo].[enumWaterTankLocation] ([waterTankLocationId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_9]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_9] FOREIGN KEY ([parkingSlotId]) REFERENCES [dbo].[mstParkingSlot] ([parkingSlotId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_10]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_10] FOREIGN KEY ([waterSupplyAccessibilityId]) REFERENCES [dbo].[enumServiceAccessibilityType] ([serviceAccessibilityId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_11]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_11] FOREIGN KEY ([garbagServiceAccessibilityId]) REFERENCES [dbo].[enumServiceAccessibilityType] ([serviceAccessibilityId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_12]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_12] FOREIGN KEY ([streetLightAccessibilityId]) REFERENCES [dbo].[enumServiceAccessibilityType] ([serviceAccessibilityId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingDetail_ToTable_13]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_13] FOREIGN KEY ([floorTypeId]) REFERENCES [dbo].[enumFloorType] ([floorTypeId]);


GO
PRINT N'Creating [dbo].[mstBuildingDetail].[advanceInfoFedBy].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'who entered advance info/userid', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'mstBuildingDetail', @level2type = N'COLUMN', @level2name = N'advanceInfoFedBy';


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_3];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_1];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_2];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_4];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_5];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_6];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_7];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_8];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_9];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_10];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_11];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_12];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_13];


GO
PRINT N'Update complete.';


GO
