CREATE TABLE [dbo].[tblWaterBillChangeHistory]
(
	[waterBillChangeHistoryId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [waterMeterReadingId] BIGINT NOT NULL,
    [transactionId] BIGINT NOT NULL, 
    [currentAmount] DECIMAL(18, 2) NOT NULL, 
    [newAmount] DECIMAL(18, 2) NOT NULL, 
    [oldPreviousReading] INT NOT NULL, 
    [newPreviousReading] INT NOT NULL, 
    [oldReading] INT NOT NULL, 
    [newReading] INT NOT NULL, 
    [oldUnit] INT NOT NULL, 
    [newUnit] INT NOT NULL, 
    [oldWaterConnectionTypeId] INT NOT NULL, 
    [newWaterConnectionTypeId] INT NOT NULL, 
    [oldStdConsumption] INT NOT NULL, 
    [newStdConsumption] INT NOT NULL, 
    [oldSewerage] BIT NOT NULL, 
    [newSewerage] BIT NOT NULL, 
    [oldConsumption] INT NOT NULL, 
    [newConsumption] INT NOT NULL, 
    [waterBillEditReasonId] INT NOT NULL, 
    [createdOn] DATETIME NOT NULL, 
    [createdBy] INT NOT NULL,
  
    CONSTRAINT [FK_tblWaterBillChangeHistory_ToTable] FOREIGN KEY ([waterMeterReadingId]) REFERENCES [tblWaterMeterReading]([waterMeterReadingId]), 
    CONSTRAINT [FK_tblWaterBillChangeHistory_ToTable_1] FOREIGN KEY ([transactionId]) REFERENCES [tblTransactionDetail]([transactionId]), 
    CONSTRAINT [FK_tblWaterBillChangeHistory_ToTable_2] FOREIGN KEY ([oldWaterConnectionTypeId]) REFERENCES [mstWaterConnectionType]([waterConnectionTypeId]), 
    CONSTRAINT [FK_tblWaterBillChangeHistory_ToTable_3] FOREIGN KEY ([newWaterConnectionTypeId]) REFERENCES [mstWaterConnectionType]([waterConnectionTypeId]), 
    CONSTRAINT [FK_tblWaterBillChangeHistory_ToTable_4] FOREIGN KEY ([waterBillEditReasonId]) REFERENCES [enumWaterBillEditReason]([waterBillEditReasonId]), 
)
