/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblDemand_ToTable_8]...';


GO
ALTER TABLE [dbo].[tblDemand] DROP CONSTRAINT [FK_tblDemand_ToTable_8];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblLedger_ToTable_3]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_3];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblLandLeaseDemandDetail_ToTable]...';


GO
ALTER TABLE [dbo].[tblLandLeaseDemandDetail] DROP CONSTRAINT [FK_tblLandLeaseDemandDetail_ToTable];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblLandLeaseDemandDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblLandLeaseDemandDetail] DROP CONSTRAINT [FK_tblLandLeaseDemandDetail_ToTable_1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblLandLeaseDemandDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblLandLeaseDemandDetail] DROP CONSTRAINT [FK_tblLandLeaseDemandDetail_ToTable_2];


GO
PRINT N'Starting rebuilding table [dbo].[tblLandLeaseDemandDetail]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tblLandLeaseDemandDetail] (
    [landLeaseDemandDetailId]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [landLeaseId]              INT             NOT NULL,
    [demandYear]               INT             NOT NULL,
    [demandDays]               INT             NOT NULL,
    [demandGenerateScheduleId] INT             NOT NULL,
    [installmentAmount]        DECIMAL (18, 2) NOT NULL,
    [demandNoId]               BIGINT          NOT NULL,
    [createdBy]                INT             NOT NULL,
    [createdOn]                DATETIME        NOT NULL,
    [modifiedBy]               INT             NULL,
    [modifiedOn]               DATETIME        NULL,
    [installmentDate]          DATE            NOT NULL,
    PRIMARY KEY CLUSTERED ([landLeaseDemandDetailId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tblLandLeaseDemandDetail])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblLandLeaseDemandDetail] ON;
        INSERT INTO [dbo].[tmp_ms_xx_tblLandLeaseDemandDetail] ([landLeaseDemandDetailId], [landLeaseId], [demandYear], [demandDays], [demandGenerateScheduleId], [installmentAmount], [demandNoId], [createdBy], [createdOn], [modifiedBy], [modifiedOn], [installmentDate])
        SELECT   [landLeaseDemandDetailId],
                 [landLeaseId],
                 [demandYear],
                 [demandDays],
                 [demandGenerateScheduleId],
                 [installmentAmount],
                 [demandNoId],
                 [createdBy],
                 [createdOn],
                 [modifiedBy],
                 [modifiedOn],
                 [installmentDate]
        FROM     [dbo].[tblLandLeaseDemandDetail]
        ORDER BY [landLeaseDemandDetailId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblLandLeaseDemandDetail] OFF;
    END

DROP TABLE [dbo].[tblLandLeaseDemandDetail];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tblLandLeaseDemandDetail]', N'tblLandLeaseDemandDetail';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblDemand_ToTable_8]...';


GO
ALTER TABLE [dbo].[tblDemand] WITH NOCHECK
    ADD CONSTRAINT [FK_tblDemand_ToTable_8] FOREIGN KEY ([landLeaseDemandDetailId]) REFERENCES [dbo].[tblLandLeaseDemandDetail] ([landLeaseDemandDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblLedger_ToTable_3]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_3] FOREIGN KEY ([landLeaseDemandDetailId]) REFERENCES [dbo].[tblLandLeaseDemandDetail] ([landLeaseDemandDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblLandLeaseDemandDetail_ToTable]...';


GO
ALTER TABLE [dbo].[tblLandLeaseDemandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLandLeaseDemandDetail_ToTable] FOREIGN KEY ([landLeaseId]) REFERENCES [dbo].[tblLandLease] ([landLeaseId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblLandLeaseDemandDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblLandLeaseDemandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLandLeaseDemandDetail_ToTable_1] FOREIGN KEY ([demandGenerateScheduleId]) REFERENCES [dbo].[enumDemandGenerateSchedule] ([demandGenerateScheduleId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblLandLeaseDemandDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblLandLeaseDemandDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLandLeaseDemandDetail_ToTable_2] FOREIGN KEY ([demandNoId]) REFERENCES [dbo].[tblDemandNo] ([demandNoId]);


GO
PRINT N'Refreshing Procedure [dbo].[GetLandLeaseDemandScheduleMonthly]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetLandLeaseDemandScheduleMonthly]';


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[tblDemand] WITH CHECK CHECK CONSTRAINT [FK_tblDemand_ToTable_8];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_3];

ALTER TABLE [dbo].[tblLandLeaseDemandDetail] WITH CHECK CHECK CONSTRAINT [FK_tblLandLeaseDemandDetail_ToTable];

ALTER TABLE [dbo].[tblLandLeaseDemandDetail] WITH CHECK CHECK CONSTRAINT [FK_tblLandLeaseDemandDetail_ToTable_1];

ALTER TABLE [dbo].[tblLandLeaseDemandDetail] WITH CHECK CHECK CONSTRAINT [FK_tblLandLeaseDemandDetail_ToTable_2];


GO
PRINT N'Update complete.';


GO
