/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [dbo].[mstTaxTypeClassification].[taxTypeClassification] is being dropped, data loss could occur.

The column [dbo].[mstTaxTypeClassification].[taxTypeClassificationName] on table [dbo].[mstTaxTypeClassification] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [dbo].[mstTaxTypeClassification])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__5A4F643B];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__floor__5B438874];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__5C37ACAD];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__floor__5D2BD0E6];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__noOfU__5E1FF51F];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__floor__5F141958];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__noOfr__60083D91];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__taxPa__60FC61CA];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__unitO__61F08603];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__isMai__62E4AA3C];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__creat__63D8CE75];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__creat__64CCF2AE];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__65C116E7];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__66B53B20];


GO
PRINT N'Dropping unnamed constraint on [dbo].[mstBuildingUnitDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__trans__67A95F59];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingUnitDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingUnitDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_1];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingUnitDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_2];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingUnitDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_3];


GO
PRINT N'Dropping [dbo].[FK_mstBuildingUnitDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_4];


GO
PRINT N'Dropping [dbo].[FK_mstTaxPeriod_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstTaxPeriod] DROP CONSTRAINT [FK_mstTaxPeriod_ToTable_1];


GO
PRINT N'Starting rebuilding table [dbo].[mstBuildingUnitDetail]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_mstBuildingUnitDetail] (
    [buildingUnitDetailId]  INT             IDENTITY (1, 1) NOT NULL,
    [buildingDetailId]      INT             NOT NULL,
    [buildingUnitClassId]   INT             DEFAULT NULL NOT NULL,
    [floorNameId]           INT             DEFAULT NULL NOT NULL,
    [buildingUnitUseTypeId] INT             DEFAULT NULL NOT NULL,
    [floorNo]               VARCHAR (45)    DEFAULT NULL NOT NULL,
    [noOfUnit]              INT             DEFAULT '1' NULL,
    [floorArea]             DECIMAL (10, 2) DEFAULT NULL NOT NULL,
    [noOfrooms]             INT             DEFAULT NULL NOT NULL,
    [taxPayerId]            INT             DEFAULT NULL NULL,
    [unitOwnerTypeId]       INT             DEFAULT NULL NOT NULL,
    [isMainOwner]           BIT             DEFAULT NULL NOT NULL,
    [createdBy]             INT             DEFAULT NULL NULL,
    [createdOn]             DATE            DEFAULT NULL NULL,
    [modifiedBy]            INT             DEFAULT NULL NULL,
    [modifiedOn]            DATE            DEFAULT NULL NULL,
    [transferStatusId]      TINYINT         DEFAULT NULL NULL,
    PRIMARY KEY CLUSTERED ([buildingUnitDetailId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[mstBuildingUnitDetail])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstBuildingUnitDetail] ON;
        INSERT INTO [dbo].[tmp_ms_xx_mstBuildingUnitDetail] ([buildingUnitDetailId], [buildingDetailId], [buildingUnitClassId], [floorNameId], [buildingUnitUseTypeId], [floorNo], [noOfUnit], [floorArea], [noOfrooms], [taxPayerId], [unitOwnerTypeId], [isMainOwner], [createdBy], [createdOn], [modifiedBy], [modifiedOn], [transferStatusId])
        SELECT   [buildingUnitDetailId],
                 [buildingDetailId],
                 [buildingUnitClassId],
                 [floorNameId],
                 [buildingUnitUseTypeId],
                 [floorNo],
                 [noOfUnit],
                 [floorArea],
                 [noOfrooms],
                 [taxPayerId],
                 [unitOwnerTypeId],
                 [isMainOwner],
                 [createdBy],
                 [createdOn],
                 [modifiedBy],
                 [modifiedOn],
                 [transferStatusId]
        FROM     [dbo].[mstBuildingUnitDetail]
        ORDER BY [buildingUnitDetailId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstBuildingUnitDetail] OFF;
    END

DROP TABLE [dbo].[mstBuildingUnitDetail];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_mstBuildingUnitDetail]', N'mstBuildingUnitDetail';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[mstTaxTypeClassification]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_mstTaxTypeClassification] (
    [taxTypeClassificationId]   INT           IDENTITY (1, 1) NOT NULL,
    [taxTypeClassificationName] VARCHAR (350) NOT NULL,
    [taxTypeDescription]        VARCHAR (350) NULL,
    [isActive]                  BIT           NOT NULL,
    [createdBy]                 INT           NOT NULL,
    [createdOn]                 DATETIME      NOT NULL,
    [modifiedBy]                INT           NULL,
    [modifiedOn]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([taxTypeClassificationId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[mstTaxTypeClassification])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstTaxTypeClassification] ON;
        INSERT INTO [dbo].[tmp_ms_xx_mstTaxTypeClassification] ([taxTypeClassificationId], [taxTypeDescription], [isActive], [createdBy], [createdOn], [modifiedBy], [modifiedOn])
        SELECT   [taxTypeClassificationId],
                 [taxTypeDescription],
                 [isActive],
                 [createdBy],
                 [createdOn],
                 [modifiedBy],
                 [modifiedOn]
        FROM     [dbo].[mstTaxTypeClassification]
        ORDER BY [taxTypeClassificationId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstTaxTypeClassification] OFF;
    END

DROP TABLE [dbo].[mstTaxTypeClassification];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_mstTaxTypeClassification]', N'mstTaxTypeClassification';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[FK_mstBuildingUnitDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable] FOREIGN KEY ([buildingDetailId]) REFERENCES [dbo].[mstBuildingDetail] ([buildingDetailId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingUnitDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_1] FOREIGN KEY ([buildingUnitUseTypeId]) REFERENCES [dbo].[mstBuildingUnitUseType] ([buildingUnitUseTypeId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingUnitDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_2] FOREIGN KEY ([floorNameId]) REFERENCES [dbo].[mstFloorName] ([floorNameId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingUnitDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_3] FOREIGN KEY ([buildingUnitClassId]) REFERENCES [dbo].[mstBuildingUnitClass] ([buildingUnitClassId]);


GO
PRINT N'Creating [dbo].[FK_mstBuildingUnitDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_4] FOREIGN KEY ([unitOwnerTypeId]) REFERENCES [dbo].[enumUnitOwnerType] ([unitOwnerTypeId]);


GO
PRINT N'Creating [dbo].[FK_mstTaxPeriod_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstTaxPeriod] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPeriod_ToTable_1] FOREIGN KEY ([taxTypeClassificationId]) REFERENCES [dbo].[mstTaxTypeClassification] ([taxTypeClassificationId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_1];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_2];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_3];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_4];

ALTER TABLE [dbo].[mstTaxPeriod] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPeriod_ToTable_1];


GO
PRINT N'Update complete.';


GO
