/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key 4ae71923-dd34-47e1-9cd1-beef21014929, a76b667c-3903-431c-a763-5bbf3e8202f7 is skipped, element [dbo].[trnOccupancyCertificateApplication].[ocForId] (SqlSimpleColumn) will not be renamed to isUnitOC';


GO
PRINT N'Rename refactoring operation with key 505b9c78-ca71-4427-88ab-f6e19579ffa8, 71c9ebb4-9cd3-477a-9bbc-902567bea54f, 79762b0d-398d-4612-80f5-aa8002df3fa4 is skipped, element [dbo].[trnOccupancyCertificateApplication].[ttin] (SqlSimpleColumn) will not be renamed to unitOrBuildingNo';


GO
PRINT N'Rename refactoring operation with key 3f190a8a-7966-45e0-a498-f249feaafeda is skipped, element [dbo].[trnOccupancyCertificateApplication].[building] (SqlSimpleColumn) will not be renamed to buildingUnitDetailId';


GO
PRINT N'Rename refactoring operation with key 82a59fe4-4721-432d-9064-1cdb8400b556 is skipped, element [dbo].[trnOccupancyCertificateApplication].[plotNo] (SqlSimpleColumn) will not be renamed to buildingDetailId';


GO
PRINT N'Starting rebuilding table [dbo].[enumOccupancyType]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_enumOccupancyType] (
    [occupancyTypeId] INT          IDENTITY (3, 1) NOT NULL,
    [occupancyType]   VARCHAR (45) NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_enumoccupancytype_OccupancyTypeID1] PRIMARY KEY CLUSTERED ([occupancyTypeId] ASC) ON [PRIMARY]
) ON [PRIMARY];

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[enumOccupancyType])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_enumOccupancyType] ON;
        INSERT INTO [dbo].[tmp_ms_xx_enumOccupancyType] ([occupancyTypeId], [occupancyType])
        SELECT   [occupancyTypeId],
                 [occupancyType]
        FROM     [dbo].[enumOccupancyType]
        ORDER BY [occupancyTypeId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_enumOccupancyType] OFF;
    END

DROP TABLE [dbo].[enumOccupancyType];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_enumOccupancyType]', N'enumOccupancyType';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_enumoccupancytype_OccupancyTypeID1]', N'PK_enumoccupancytype_OccupancyTypeID', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering Table [dbo].[trnConstructionApprovalApplicationFeeDetail]...';


GO
ALTER TABLE [dbo].[trnConstructionApprovalApplicationFeeDetail] ALTER COLUMN [g2cApplicationNo] VARCHAR (150) NOT NULL;


GO
PRINT N'Creating Table [dbo].[trnOccupancyCertificateApplication]...';


GO
CREATE TABLE [dbo].[trnOccupancyCertificateApplication] (
    [OccupancyCertificateApplicationId] INT           IDENTITY (1, 1) NOT NULL,
    [occupancyTypeId]                   INT           NOT NULL,
    [landDetailId]                      INT           NOT NULL,
    [buildingDetailId]                  INT           NULL,
    [buildingUnitDetailId]              INT           NULL,
    [taxPayerId]                        INT           NOT NULL,
    [yearOfConstruction]                INT           NOT NULL,
    [dateOfFinalInspection]             DATE          NOT NULL,
    [isUnitOC]                          BIT           NOT NULL,
    [unitOrBuildingNo]                  VARCHAR (150) NULL,
    [g2cApplicationNo]                  VARCHAR (150) NOT NULL,
    [createdBy]                         INT           NOT NULL,
    [creationOn]                        DATE          NOT NULL,
    [modifiedBy]                        INT           NULL,
    [modifiedOn]                        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OccupancyCertificateApplicationId] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable] FOREIGN KEY ([occupancyTypeId]) REFERENCES [dbo].[enumOccupancyType] ([occupancyTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_1]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_1] FOREIGN KEY ([buildingUnitDetailId]) REFERENCES [dbo].[mstBuildingUnitDetail] ([buildingUnitDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_2]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_2] FOREIGN KEY ([buildingDetailId]) REFERENCES [dbo].[mstBuildingDetail] ([buildingDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_3]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_3] FOREIGN KEY ([taxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_4]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_4] FOREIGN KEY ([landDetailId]) REFERENCES [dbo].[mstLandDetail] ([landDetailId]);


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '4ae71923-dd34-47e1-9cd1-beef21014929')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('4ae71923-dd34-47e1-9cd1-beef21014929')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '505b9c78-ca71-4427-88ab-f6e19579ffa8')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('505b9c78-ca71-4427-88ab-f6e19579ffa8')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '3f190a8a-7966-45e0-a498-f249feaafeda')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('3f190a8a-7966-45e0-a498-f249feaafeda')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'a76b667c-3903-431c-a763-5bbf3e8202f7')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('a76b667c-3903-431c-a763-5bbf3e8202f7')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '82a59fe4-4721-432d-9064-1cdb8400b556')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('82a59fe4-4721-432d-9064-1cdb8400b556')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '71c9ebb4-9cd3-477a-9bbc-902567bea54f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('71c9ebb4-9cd3-477a-9bbc-902567bea54f')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '79762b0d-398d-4612-80f5-aa8002df3fa4')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('79762b0d-398d-4612-80f5-aa8002df3fa4')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_1];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_2];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_3];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_4];


GO
PRINT N'Update complete.';


GO
