/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__build__48A5B54C]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__48A5B54C];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__floor__47B19113]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__floor__47B19113];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__build__46BD6CDA]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__46BD6CDA];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__isAct__55FFB06A]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__isAct__55FFB06A];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__trans__550B8C31]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__trans__550B8C31];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__modif__541767F8]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__541767F8];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__modif__532343BF]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__532343BF];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__creat__522F1F86]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__creat__522F1F86];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__creat__513AFB4D]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__creat__513AFB4D];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__isMai__5046D714]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__isMai__5046D714];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__unitO__4F52B2DB]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__unitO__4F52B2DB];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__taxPa__4E5E8EA2]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__taxPa__4E5E8EA2];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__noOfr__4D6A6A69]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__noOfr__4D6A6A69];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__floor__4C764630]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__floor__4C764630];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__noOfU__4B8221F7]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__noOfU__4B8221F7];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__flatN__4A8DFDBE]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__flatN__4A8DFDBE];


GO
PRINT N'Dropping Default Constraint [dbo].[DF__tmp_ms_xx__floor__4999D985]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [DF__tmp_ms_xx__floor__4999D985];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_1]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] DROP CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_2];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_3];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_4];


GO
PRINT N'Starting rebuilding table [dbo].[mstBuildingUnitDetail]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_mstBuildingUnitDetail] (
    [buildingUnitDetailId]  INT             IDENTITY (1, 1) NOT NULL,
    [buildingDetailId]      INT             NOT NULL,
    [buildingUnitClassId]   INT             DEFAULT NULL NOT NULL,
    [floorNameId]           INT             DEFAULT NULL NOT NULL,
    [buildingUnitUseTypeId] INT             DEFAULT NULL NOT NULL,
    [isRegularized]         BIT             NOT NULL,
    [floorNo]               VARCHAR (45)    DEFAULT NULL NOT NULL,
    [flatNo]                VARCHAR (50)    DEFAULT NULL NOT NULL,
    [noOfUnit]              INT             DEFAULT '1' NOT NULL,
    [floorArea]             DECIMAL (10, 2) DEFAULT NULL NOT NULL,
    [noOfrooms]             INT             DEFAULT NULL NOT NULL,
    [taxPayerId]            INT             DEFAULT NULL NOT NULL,
    [landDetailId]          INT             NOT NULL,
    [unitOwnerTypeId]       INT             DEFAULT NULL NOT NULL,
    [isMainOwner]           BIT             DEFAULT NULL NOT NULL,
    [createdBy]             INT             DEFAULT NULL NULL,
    [createdOn]             DATE            DEFAULT NULL NULL,
    [modifiedBy]            INT             DEFAULT NULL NULL,
    [modifiedOn]            DATE            DEFAULT NULL NULL,
    [transferStatusId]      TINYINT         DEFAULT NULL NULL,
    [isActive]              BIT             DEFAULT 1 NOT NULL,
    PRIMARY KEY CLUSTERED ([buildingUnitDetailId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[mstBuildingUnitDetail])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstBuildingUnitDetail] ON;
        INSERT INTO [dbo].[tmp_ms_xx_mstBuildingUnitDetail] ([buildingUnitDetailId], [buildingDetailId], [buildingUnitClassId], [floorNameId], [buildingUnitUseTypeId], [isRegularized], [floorNo], [flatNo], [noOfUnit], [floorArea], [noOfrooms], [taxPayerId], [landDetailId], [unitOwnerTypeId], [isMainOwner], [createdBy], [createdOn], [modifiedBy], [modifiedOn], [transferStatusId], [isActive])
        SELECT   [buildingUnitDetailId],
                 [buildingDetailId],
                 [buildingUnitClassId],
                 [floorNameId],
                 [buildingUnitUseTypeId],
                 [isRegularized],
                 [floorNo],
                 [flatNo],
                 [noOfUnit],
                 [floorArea],
                 [noOfrooms],
                 [taxPayerId],
                 [landDetailId],
                 [unitOwnerTypeId],
                 [isMainOwner],
                 [createdBy],
                 [createdOn],
                 [modifiedBy],
                 [modifiedOn],
                 [transferStatusId],
                 [isActive]
        FROM     [dbo].[mstBuildingUnitDetail]
        ORDER BY [buildingUnitDetailId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstBuildingUnitDetail] OFF;
    END

DROP TABLE [dbo].[mstBuildingUnitDetail];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_mstBuildingUnitDetail]', N'mstBuildingUnitDetail';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_1]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_1] FOREIGN KEY ([buildingUnitDetailId]) REFERENCES [dbo].[mstBuildingUnitDetail] ([buildingUnitDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable] FOREIGN KEY ([buildingDetailId]) REFERENCES [dbo].[mstBuildingDetail] ([buildingDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_1] FOREIGN KEY ([buildingUnitUseTypeId]) REFERENCES [dbo].[mstBuildingUnitUseType] ([buildingUnitUseTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_2] FOREIGN KEY ([floorNameId]) REFERENCES [dbo].[mstFloorName] ([floorNameId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_3] FOREIGN KEY ([buildingUnitClassId]) REFERENCES [dbo].[mstBuildingUnitClass] ([buildingUnitClassId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_4] FOREIGN KEY ([unitOwnerTypeId]) REFERENCES [dbo].[enumUnitOwnerType] ([unitOwnerTypeId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_1];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_1];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_2];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_3];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_4];


GO
PRINT N'Update complete.';


GO
