CREATE TABLE [dbo].[trnWaterMeterReading]
(
	[trnWaterMeterReadingId] INT NOT NULL PRIMARY KEY IDENTITY,
	[trnWaterConnectionId] BIGINT NOT NULL, 
    [waterConnectionTypeId] INT NOT NULL,    
    [waterMeterTypeId] INT NOT NULL,     
    [waterLineTypeId] INT NOT NULL, 
    [waterConnectionStatusId] INT NOT NULL,
    [bucid] INT NULL, 
    [reading] INT NOT NULL, 
    [previousReading] INT NOT NULL, 
    [previousReadingDate] DATE NOT NULL,    
    [readBy] INT NOT NULL, 
    [readingDate] DATE NOT NULL,    
    [noOfUnit] INT NOT NULL,   
    [consumption] INT NOT NULL,  
    [standardConsumption] INT NULL, 
    [isPermanentConnection] BIT NOT NULL, 
    [sewerage] BIT NOT NULL, 
    [solidWaste] BIT NOT NULL,         
    [remarks] VARCHAR(250) NULL,  
    [billingAddress] VARCHAR(350) NOT NULL, 
      [transactionId] BIGINT NULL, 
    [primaryMobileNo] VARCHAR(150) NOT NULL, 
    [secondaryMobileNo] VARCHAR(150) NULL, 
    CONSTRAINT [FK_trnWaterMeterReading_ToTable] FOREIGN KEY ([trnWaterConnectionId]) REFERENCES [trnWaterConnection]([trnWaterConnectionId]), 
    CONSTRAINT [FK_trnWaterMeterReading_ToTable_1] FOREIGN KEY ([waterConnectionTypeId]) REFERENCES [mstWaterConnectionType]([waterConnectionTypeId]), 
    CONSTRAINT [FK_trnWaterMeterReading_ToTable_2] FOREIGN KEY ([waterMeterTypeId]) REFERENCES [mstWaterMeterType]([waterMeterTypeId]), 
    CONSTRAINT [FK_trnWaterMeterReading_ToTable_3] FOREIGN KEY ([waterLineTypeId]) REFERENCES [mstWaterLineType]([waterLineTypeId]), 
    CONSTRAINT [FK_trnWaterMeterReading_ToTable_4] FOREIGN KEY ([waterConnectionStatusId]) REFERENCES [enumWaterConnectionStatus]([waterConnectionStatusId]), 
    
)
