
CREATE TABLE [dbo].[enumECUseType](
	[ecUseTypeID] [int] IDENTITY(1,1) NOT NULL,
	[ecUseType] [varchar](45) NOT NULL,
 CONSTRAINT [PK_enumecusetype_EcUseTypeID] PRIMARY KEY CLUSTERED 
(
	[ecUseTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO