/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [dbo].[trnConstructionApprovalApplicationFeeDetail].[thramNo] is being dropped, data loss could occur.

The column [dbo].[trnConstructionApprovalApplicationFeeDetail].[ttin] is being dropped, data loss could occur.

The type for column landOwnershipId in table [dbo].[trnConstructionApprovalApplicationFeeDetail] is currently  VARCHAR (50) NOT NULL but is being changed to  INT NOT NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  INT NOT NULL.
*/

IF EXISTS (select top 1 1 from [dbo].[trnConstructionApprovalApplicationFeeDetail])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'The following operation was generated from a refactoring log file 69238549-51c9-4a26-bd3e-11a80e9f1684, 5fc2e5ee-49bd-462a-a4e4-fbf5c81c609a';

PRINT N'Rename [dbo].[trnConstructionApprovalApplicationFeeDetail].[plotNo] to landOwnershipId';


GO
EXECUTE sp_rename @objname = N'[dbo].[trnConstructionApprovalApplicationFeeDetail].[plotNo]', @newname = N'landOwnershipId', @objtype = N'COLUMN';


GO
PRINT N'Altering Table [dbo].[trnConstructionApprovalApplicationFeeDetail]...';


GO
ALTER TABLE [dbo].[trnConstructionApprovalApplicationFeeDetail] DROP COLUMN [thramNo], COLUMN [ttin];


GO
ALTER TABLE [dbo].[trnConstructionApprovalApplicationFeeDetail] ALTER COLUMN [landOwnershipId] INT NOT NULL;


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnConstructionApprovalApplicationFeeDetail_ToTable]...';


GO
ALTER TABLE [dbo].[trnConstructionApprovalApplicationFeeDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnConstructionApprovalApplicationFeeDetail_ToTable] FOREIGN KEY ([landOwnershipId]) REFERENCES [dbo].[tblLandOwnershipDetail] ([landOwnershipId]);


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '69238549-51c9-4a26-bd3e-11a80e9f1684')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('69238549-51c9-4a26-bd3e-11a80e9f1684')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5fc2e5ee-49bd-462a-a4e4-fbf5c81c609a')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5fc2e5ee-49bd-462a-a4e4-fbf5c81c609a')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[trnConstructionApprovalApplicationFeeDetail] WITH CHECK CHECK CONSTRAINT [FK_trnConstructionApprovalApplicationFeeDetail_ToTable];


GO
PRINT N'Update complete.';


GO
