/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [dbo].[mstBuildingDetail].[g2cApplicationNo] on table [dbo].[mstBuildingDetail] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [dbo].[mstBuildingDetail])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The column [dbo].[trnOccupancyCertificateApplication].[g2cApplicationNo] is being dropped, data loss could occur.

The column [dbo].[trnOccupancyCertificateApplication].[isUnitOC] is being dropped, data loss could occur.

The column [dbo].[trnOccupancyCertificateApplication].[unitOrBuildingNo] is being dropped, data loss could occur.

The column [dbo].[trnOccupancyCertificateApplication].[yearOfConstruction] is being dropped, data loss could occur.

The column [dbo].[trnOccupancyCertificateApplication].[logoSignMapId] on table [dbo].[trnOccupancyCertificateApplication] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column [dbo].[trnOccupancyCertificateApplication].[ocReferenceNo] on table [dbo].[trnOccupancyCertificateApplication] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column buildingDetailId on table [dbo].[trnOccupancyCertificateApplication] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [dbo].[trnOccupancyCertificateApplication])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Rename refactoring operation with key 10c61620-4488-482f-ae86-1c669c7fd36c is skipped, element [dbo].[trnOccupancyCertificateApplication].[OccupancyCertificateApplicationId] (SqlSimpleColumn) will not be renamed to occupancyCertificateApplicationId';


GO
PRINT N'Rename refactoring operation with key b90ec218-10e0-4b5f-b95e-a1328b9cd362 is skipped, element [dbo].[occupancyCertificateUnitMap].[Id] (SqlSimpleColumn) will not be renamed to occupancyCertificateUnitMapId';


GO
PRINT N'Rename refactoring operation with key 142b6ae5-96ed-4c62-9d9d-2ecfbc93b39f is skipped, element [dbo].[occupancyCertificateUnitMap].[occupancyCertificat] (SqlSimpleColumn) will not be renamed to occupancyCertificateApplicationId';


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__struc__2A212E2C];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__mater__2B155265];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__1DBB5747];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__1EAF7B80];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__garba__1FA39FB9];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__stree__2097C3F2];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__218BE82B];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__yearO__22800C64];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__246854D6];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__payme__255C790F];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__2374309D];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__water__26509D48];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__sewer__2744C181];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__attic__2838E5BA];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__struc__292D09F3];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__archF__2C09769E];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__roofi__2CFD9AD7];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__roofi__2DF1BF10];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__tradi__2EE5E349];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__build__2FDA0782];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__bound__30CE2BBB];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__plant__31C24FF4];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__water__32B6742D];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__numbe__33AA9866];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__parki__349EBC9F];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__fireE__3592E0D8];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__water__36870511];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__roadA__377B294A];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__drain__386F4D83];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__dateO__396371BC];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__3A5795F5];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__3B4BBA2E];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__occup__3C3FDE67];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__advan__3D3402A0];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__advan__3E2826D9];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__remar__3F1C4B12];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__40106F4B];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__41049384];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__trans__41F8B7BD];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__42ECDBF6];


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[mstBuildingDetail]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [DF__tmp_ms_xx__modif__43E1002F];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_2]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] DROP CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_2];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_10]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_10];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_11]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_11];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_12]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_12];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_13]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_13];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_2];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_3];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_4];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_5]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_5];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_6]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_6];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_7]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_7];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_8]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_8];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_9]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] DROP CONSTRAINT [FK_mstBuildingDetail_ToTable_9];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] DROP CONSTRAINT [FK_mstBuildingUnitDetail_ToTable];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] DROP CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_1]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] DROP CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_3]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] DROP CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_3];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_4]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] DROP CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_4];


GO
PRINT N'Starting rebuilding table [dbo].[mstBuildingDetail]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_mstBuildingDetail] (
    [buildingDetailId]              INT             IDENTITY (1, 1) NOT NULL,
    [landDetailId]                  INT             NOT NULL,
    [buildingClassId]               INT             DEFAULT '1' NOT NULL,
    [storyTypeId]                   INT             NOT NULL,
    [buildingNo]                    VARCHAR (250)   DEFAULT NULL NULL,
    [buildupArea]                   DECIMAL (10, 2) NOT NULL,
    [plinthArea]                    DECIMAL (18, 2) NULL,
    [noOfUnits]                     INT             NOT NULL,
    [numberOfFloors]                INT             NOT NULL,
    [garbagServiceAccessibilityId]  INT             DEFAULT NULL NULL,
    [streetLightAccessibilityId]    INT             DEFAULT NULL NULL,
    [occupancyCertificateNo]        VARCHAR (256)   DEFAULT NULL NULL,
    [constructionTypeId]            INT             NOT NULL,
    [yearOfConstruction]            INT             DEFAULT NULL NULL,
    [occupancyCertificateIssued]    BIT             DEFAULT NULL NULL,
    [occupancyCertificateIssueDate] DATE            DEFAULT NULL NULL,
    [paymentCompletionStatusId]     BIT             DEFAULT '0' NOT NULL,
    [waterConnection]               BIT             DEFAULT NULL NULL,
    [sewerageConnection]            BIT             DEFAULT NULL NULL,
    [attic]                         BIT             DEFAULT NULL NULL,
    [structureCategoryId]           INT             DEFAULT NULL NULL,
    [structureTypeId]               INT             DEFAULT NULL NULL,
    [materialTypeId]                INT             DEFAULT NULL NULL,
    [archFeature]                   BIT             DEFAULT NULL NULL,
    [roofing]                       BIT             DEFAULT NULL NULL,
    [roofingTypeId]                 INT             DEFAULT NULL NULL,
    [traditionalPainting]           BIT             DEFAULT NULL NULL,
    [buildingColourId]              INT             DEFAULT NULL NULL,
    [boundaryTypeId]                INT             DEFAULT NULL NULL,
    [plantation]                    BIT             DEFAULT NULL NULL,
    [waterTankLocationId]           INT             DEFAULT NULL NULL,
    [numberDisplayed]               BIT             DEFAULT NULL NULL,
    [parkingSlotId]                 INT             DEFAULT NULL NULL,
    [fireExtingusher]               BIT             DEFAULT NULL NULL,
    [waterSupplyAccessibilityId]    INT             DEFAULT NULL NULL,
    [roadAccess]                    BIT             DEFAULT NULL NULL,
    [drainToStormWaterDrain]        BIT             DEFAULT NULL NULL,
    [dateOfFinalInspection]         DATE            DEFAULT NULL NULL,
    [occupancyAlteredOn]            DATE            DEFAULT NULL NULL,
    [occupancyAlteredBy]            INT             DEFAULT NULL NULL,
    [occupancyReferenceId]          INT             DEFAULT NULL NULL,
    [advanceInfoFedBy]              INT             DEFAULT NULL NULL,
    [advanceInfoInfoFedOn]          DATE            DEFAULT NULL NULL,
    [remarks]                       VARCHAR (345)   DEFAULT NULL NULL,
    [modificationRemarks]           VARCHAR (300)   DEFAULT NULL NULL,
    [modificationReasonId]          INT             DEFAULT NULL NULL,
    [transactionId]                 INT             DEFAULT NULL NULL,
    [g2cApplicationNo]              VARCHAR (150)   NOT NULL,
    [createdBy]                     INT             NOT NULL,
    [createdOn]                     DATETIME        NOT NULL,
    [modifiedBy]                    INT             DEFAULT NULL NULL,
    [modifiedOn]                    DATETIME        DEFAULT NULL NULL,
    PRIMARY KEY CLUSTERED ([buildingDetailId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[mstBuildingDetail])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstBuildingDetail] ON;
        INSERT INTO [dbo].[tmp_ms_xx_mstBuildingDetail] ([buildingDetailId], [landDetailId], [buildingClassId], [storyTypeId], [buildingNo], [buildupArea], [plinthArea], [noOfUnits], [numberOfFloors], [garbagServiceAccessibilityId], [streetLightAccessibilityId], [occupancyCertificateNo], [constructionTypeId], [yearOfConstruction], [occupancyCertificateIssued], [occupancyCertificateIssueDate], [paymentCompletionStatusId], [waterConnection], [sewerageConnection], [attic], [structureCategoryId], [structureTypeId], [materialTypeId], [archFeature], [roofing], [roofingTypeId], [traditionalPainting], [buildingColourId], [boundaryTypeId], [plantation], [waterTankLocationId], [numberDisplayed], [parkingSlotId], [fireExtingusher], [waterSupplyAccessibilityId], [roadAccess], [drainToStormWaterDrain], [dateOfFinalInspection], [occupancyAlteredOn], [occupancyAlteredBy], [occupancyReferenceId], [advanceInfoFedBy], [advanceInfoInfoFedOn], [remarks], [modificationRemarks], [modificationReasonId], [transactionId], [createdBy], [createdOn], [modifiedBy], [modifiedOn])
        SELECT   [buildingDetailId],
                 [landDetailId],
                 [buildingClassId],
                 [storyTypeId],
                 [buildingNo],
                 [buildupArea],
                 [plinthArea],
                 [noOfUnits],
                 [numberOfFloors],
                 [garbagServiceAccessibilityId],
                 [streetLightAccessibilityId],
                 [occupancyCertificateNo],
                 [constructionTypeId],
                 [yearOfConstruction],
                 [occupancyCertificateIssued],
                 [occupancyCertificateIssueDate],
                 [paymentCompletionStatusId],
                 [waterConnection],
                 [sewerageConnection],
                 [attic],
                 [structureCategoryId],
                 [structureTypeId],
                 [materialTypeId],
                 [archFeature],
                 [roofing],
                 [roofingTypeId],
                 [traditionalPainting],
                 [buildingColourId],
                 [boundaryTypeId],
                 [plantation],
                 [waterTankLocationId],
                 [numberDisplayed],
                 [parkingSlotId],
                 [fireExtingusher],
                 [waterSupplyAccessibilityId],
                 [roadAccess],
                 [drainToStormWaterDrain],
                 [dateOfFinalInspection],
                 [occupancyAlteredOn],
                 [occupancyAlteredBy],
                 [occupancyReferenceId],
                 [advanceInfoFedBy],
                 [advanceInfoInfoFedOn],
                 [remarks],
                 [modificationRemarks],
                 [modificationReasonId],
                 [transactionId],
                 [createdBy],
                 [createdOn],
                 [modifiedBy],
                 [modifiedOn]
        FROM     [dbo].[mstBuildingDetail]
        ORDER BY [buildingDetailId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstBuildingDetail] OFF;
    END

DROP TABLE [dbo].[mstBuildingDetail];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_mstBuildingDetail]', N'mstBuildingDetail';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering Table [dbo].[trnLandTransferDetail]...';


GO
ALTER TABLE [dbo].[trnLandTransferDetail] ALTER COLUMN [toTaxPayerId] VARCHAR (350) NULL;


GO
PRINT N'Starting rebuilding table [dbo].[trnOccupancyCertificateApplication]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_trnOccupancyCertificateApplication] (
    [occupancyCertificateApplicationId] INT           IDENTITY (1, 1) NOT NULL,
    [occupancyTypeId]                   INT           NOT NULL,
    [landDetailId]                      INT           NOT NULL,
    [buildingDetailId]                  INT           NOT NULL,
    [buildingUnitDetailId]              INT           NULL,
    [taxPayerId]                        INT           NOT NULL,
    [dateOfFinalInspection]             DATE          NOT NULL,
    [logoSignMapId]                     INT           NOT NULL,
    [issueDate]                         DATETIME      NULL,
    [validTillDate]                     DATETIME      NULL,
    [ocReferenceNo]                     VARCHAR (300) NOT NULL,
    [createdBy]                         INT           NOT NULL,
    [creationOn]                        DATE          NOT NULL,
    [modifiedBy]                        INT           NULL,
    [modifiedOn]                        DATETIME      NULL,
    [yr]                                INT           NULL,
    [sl]                                INT           NULL,
    PRIMARY KEY CLUSTERED ([occupancyCertificateApplicationId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[trnOccupancyCertificateApplication])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_trnOccupancyCertificateApplication] ON;
        INSERT INTO [dbo].[tmp_ms_xx_trnOccupancyCertificateApplication] ([occupancyCertificateApplicationId], [occupancyTypeId], [landDetailId], [buildingDetailId], [buildingUnitDetailId], [taxPayerId], [dateOfFinalInspection], [createdBy], [creationOn], [modifiedBy], [modifiedOn])
        SELECT   [occupancyCertificateApplicationId],
                 [occupancyTypeId],
                 [landDetailId],
                 [buildingDetailId],
                 [buildingUnitDetailId],
                 [taxPayerId],
                 [dateOfFinalInspection],
                 [createdBy],
                 [creationOn],
                 [modifiedBy],
                 [modifiedOn]
        FROM     [dbo].[trnOccupancyCertificateApplication]
        ORDER BY [occupancyCertificateApplicationId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_trnOccupancyCertificateApplication] OFF;
    END

DROP TABLE [dbo].[trnOccupancyCertificateApplication];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_trnOccupancyCertificateApplication]', N'trnOccupancyCertificateApplication';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Table [dbo].[occupancyCertificateUnitMap]...';


GO
CREATE TABLE [dbo].[occupancyCertificateUnitMap] (
    [occupancyCertificateUnitMapId]     INT IDENTITY (1, 1) NOT NULL,
    [occupancyCertificateApplicationId] INT NULL,
    [buildingUnitDetailId]              INT NULL,
    PRIMARY KEY CLUSTERED ([occupancyCertificateUnitMapId] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_2]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_2] FOREIGN KEY ([buildingDetailId]) REFERENCES [dbo].[mstBuildingDetail] ([buildingDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable] FOREIGN KEY ([landDetailId]) REFERENCES [dbo].[mstLandDetail] ([landDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_1] FOREIGN KEY ([constructionTypeId]) REFERENCES [dbo].[mstConstructionType] ([constructionTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_10]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_10] FOREIGN KEY ([waterSupplyAccessibilityId]) REFERENCES [dbo].[enumServiceAccessibilityType] ([serviceAccessibilityId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_11]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_11] FOREIGN KEY ([garbagServiceAccessibilityId]) REFERENCES [dbo].[enumServiceAccessibilityType] ([serviceAccessibilityId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_12]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_12] FOREIGN KEY ([streetLightAccessibilityId]) REFERENCES [dbo].[enumServiceAccessibilityType] ([serviceAccessibilityId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_13]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_13] FOREIGN KEY ([storyTypeId]) REFERENCES [dbo].[enumStoryType] ([storyTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_2] FOREIGN KEY ([structureCategoryId]) REFERENCES [dbo].[mstStructureCategory] ([structureCategoryId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_3] FOREIGN KEY ([structureTypeId]) REFERENCES [dbo].[mstStructureType] ([structureTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_4] FOREIGN KEY ([materialTypeId]) REFERENCES [dbo].[mstMaterialType] ([materialTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_5]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_5] FOREIGN KEY ([roofingTypeId]) REFERENCES [dbo].[mstRoofingType] ([roofingTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_6]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_6] FOREIGN KEY ([buildingColourId]) REFERENCES [dbo].[mstBuildingColour] ([buildingColourId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_7]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_7] FOREIGN KEY ([boundaryTypeId]) REFERENCES [dbo].[mstBoundaryType] ([boundaryTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_8]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_8] FOREIGN KEY ([waterTankLocationId]) REFERENCES [dbo].[enumWaterTankLocation] ([waterTankLocationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingDetail_ToTable_9]...';


GO
ALTER TABLE [dbo].[mstBuildingDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingDetail_ToTable_9] FOREIGN KEY ([parkingSlotId]) REFERENCES [dbo].[mstParkingSlot] ([parkingSlotId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstBuildingUnitDetail_ToTable]...';


GO
ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_mstBuildingUnitDetail_ToTable] FOREIGN KEY ([buildingDetailId]) REFERENCES [dbo].[mstBuildingDetail] ([buildingDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable] FOREIGN KEY ([occupancyTypeId]) REFERENCES [dbo].[enumOccupancyType] ([occupancyTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_1]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_1] FOREIGN KEY ([buildingUnitDetailId]) REFERENCES [dbo].[mstBuildingUnitDetail] ([buildingUnitDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_3]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_3] FOREIGN KEY ([taxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_4]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_4] FOREIGN KEY ([landDetailId]) REFERENCES [dbo].[mstLandDetail] ([landDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_6]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_6] FOREIGN KEY ([logoSignMapId]) REFERENCES [dbo].[mstLogoSignMap] ([logoSignMapId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnLandTransferDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[trnLandTransferDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandTransferDetail_ToTable_2] FOREIGN KEY ([fromTaxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Extended Property [dbo].[mstBuildingDetail].[advanceInfoFedBy].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'who entered advance info/userid', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'mstBuildingDetail', @level2type = N'COLUMN', @level2name = N'advanceInfoFedBy';


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '10c61620-4488-482f-ae86-1c669c7fd36c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('10c61620-4488-482f-ae86-1c669c7fd36c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'b90ec218-10e0-4b5f-b95e-a1328b9cd362')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('b90ec218-10e0-4b5f-b95e-a1328b9cd362')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '142b6ae5-96ed-4c62-9d9d-2ecfbc93b39f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('142b6ae5-96ed-4c62-9d9d-2ecfbc93b39f')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_2];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_1];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_10];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_11];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_12];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_13];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_2];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_3];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_4];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_5];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_6];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_7];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_8];

ALTER TABLE [dbo].[mstBuildingDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingDetail_ToTable_9];

ALTER TABLE [dbo].[mstBuildingUnitDetail] WITH CHECK CHECK CONSTRAINT [FK_mstBuildingUnitDetail_ToTable];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_1];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_3];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_4];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_6];

ALTER TABLE [dbo].[trnLandTransferDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandTransferDetail_ToTable_2];


GO
PRINT N'Update complete.';


GO
