/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering Procedure [dbo].[rptOnlinePaymentByFromDateToDate]...';


GO
ALTER PROCEDURE [dbo].[rptOnlinePaymentByFromDateToDate]
	@FromDate date
	,@ToDate date
AS
 SELECT  ROW_NUMBER() OVER(
 ORDER BY (select 1)) AS Sl
,FORMAT (pl.createdOn, 'dd/MM/yyyy, hh:mm') as PaymentDate
	,r.receiptNo as ReceiptNo
	,isnull(pl.paymentModeNo,'-') as PaymentModeNo
	,isnull(FORMAT (pl.paymentModeDate, 'dd/MM/yyyy'),'-')  as PaymentModeDate
	,isnull(sum(amount),0) as TotalAmount
	,FORMAT (@FromDate, 'dd/MM/yyyy') as FromDate
	,FORMAT (@ToDate, 'dd/MM/yyyy') as ToDate
	   from tblPaymentLeger pl 	  
	   left join tblReceipt r on pl.receiptId=r.receiptId
	  where 
	  convert (varchar,pl.createdOn, 112)>=convert (varchar,@FromDate, 112) 
	  and  convert (varchar,pl.createdOn, 112)<=convert (varchar,@ToDate, 112) 
	  
group by r.receiptNo,FORMAT (pl.createdOn, 'dd/MM/yyyy, hh:mm')
,pl.paymentModeNo,FORMAT (pl.paymentModeDate, 'dd/MM/yyyy')
order by r.receiptNo,PaymentDate
RETURN 0

-- exec [dbo].[rptOnlinePaymentByFromDateToDate] 20/02/2021
GO
PRINT N'Update complete.';


GO
