CREATE TABLE [dbo].[trnLandDetail]
(
	[trnFTLandDetailId] INT NOT NULL PRIMARY KEY IDENTITY,
	[transactorTypeId] INT NOT NULL, 
	[landTransferTypeId] INT NOT NULL ,
	[lapId] [int] NOT NULL,
	[demkhongId] [int] NOT NULL,
	[streetNameId] [int] not null,
	[landTypeId] [int] NOT NULL,
	[landUseSubCategoryId] [int] NOT NULL,
		[propertyTypeId] [int] NOT NULL,
	[plotNo] [varchar](145) NOT NULL,
	[landAcerage] [decimal](10, 2) NOT NULL,
	[landValue] [decimal](10, 2) NOT NULL,	
	[landPoolingRate] [decimal](10, 3) NOT NULL,
	[structureAvailable] BIT NOT NULL,
	[plotAddress] [varchar](255) NOT NULL,	
	[location] [varchar](255) NULL,	
	[IsApproved] BIT NOT NULL,
	[createdBy] [int] NOT NULL,
	[creationOn] [date] NOT NULL,
	[modifiedBy] [int] NULL,
	[modifiedOn] [datetime] NULL, 
    [vacantLandTaxApplicable] BIT NULL, 
    [garbageApplicable] BIT NULL, 
    [streetLightApplicable] BIT NULL,     
    [eSakorTransactionId] VARCHAR(250) NOT NULL, 
    CONSTRAINT [FK_trnLandDetail_ToTable] FOREIGN KEY ([lapId]) REFERENCES [mstLap]([lapId]), 
	CONSTRAINT [FK_trnLandDetail_ToTable_4] FOREIGN KEY ([demkhongId]) REFERENCES [mstDemkhong]([demkhongId]),
	CONSTRAINT [FK_trnLandDetail_ToTable_1] FOREIGN KEY ([landUseSubCategoryId]) REFERENCES [mstLandUseSubCategory]([landUseSubCategoryId]), 
    CONSTRAINT [FK_trnLandDetail_ToTable_2] FOREIGN KEY ([landTypeId]) REFERENCES [mstLandType]([landTypeId]), 
    CONSTRAINT [FK_trnLandDetail_ToTable_5] FOREIGN KEY ([streetNameId]) REFERENCES [mstStreetName]([streetNameId]), 
    CONSTRAINT [FK_trnLandDetail_ToTable_6] FOREIGN KEY ([transactorTypeId]) REFERENCES [enumTransactorType]([transactorTypeId]), 
    CONSTRAINT [FK_trnLandDetail_ToTable_3] FOREIGN KEY ([landTransferTypeId]) REFERENCES [enumLandTransferType]([landTransferTypeId]), 
 CONSTRAINT [FK_trnLandDetail_ToTable_7] FOREIGN KEY ([propertyTypeId]) REFERENCES [enumPropertyType]([propertyTypeId]), 
   
)
