CREATE TABLE [dbo].[mstLandDetail]
(
	[landDetailId] INT NOT NULL PRIMARY KEY IDENTITY,
	[lapId] [int] NULL,
	[demkhongId] [int] NULL,
	[streetNameId] [int] null,
	[landTypeId] [int] NOT NULL,
	[propertyTypeId] [int] NOT NULL,
	[landUseSubCategoryId] [int] NULL,
	[plotNo] [varchar](145) NOT NULL,
	[landAcerage] [decimal](10, 2) NOT NULL,
	[landValue] [decimal](10, 2) NOT NULL,
	[landPoolingRate] [decimal](10, 3) NOT NULL,
	[structureAvailable] BIT NOT NULL,
	[plotAddress] [varchar](255) NOT NULL,	
	[location] [varchar](255) NULL,	
	[IsApproved] BIT NOT NULL,
	[createdBy] [int] NOT NULL,
	[creationOn] [date] NOT NULL,
	[modifiedBy] [int] NULL,
	[modifiedOn] [datetime] NULL, 
	[transactionId] BIGINT NULL,
    [vacantLandTaxApplicable] BIT NOT NULL, 
    [garbageApplicable] BIT NOT NULL, 
    [streetLightApplicable] BIT NOT NULL, 
    [isSubdivided] BIT NOT NULL DEFAULT 0, 
    [lastTaxPaidYear] INT NULL, 
    [isApportioned] BIT NOT NULL DEFAULT 1, 
    [thramNo] VARCHAR(100) NULL, 
    CONSTRAINT [FK_mstLandDetail_ToTable] FOREIGN KEY ([lapId]) REFERENCES [mstLap]([lapId]), 
	CONSTRAINT [FK_mstLandDetail_ToTable_4] FOREIGN KEY ([demkhongId]) REFERENCES [mstDemkhong]([demkhongId]),
	CONSTRAINT [FK_mstLandDetail_ToTable_1] FOREIGN KEY ([landUseSubCategoryId]) REFERENCES [mstLandUseSubCategory]([landUseSubCategoryId]), 
    CONSTRAINT [FK_mstLandDetail_ToTable_2] FOREIGN KEY ([landTypeId]) REFERENCES [mstLandType]([landTypeId]), 
    CONSTRAINT [FK_mstLandDetail_ToTable_3] FOREIGN KEY ([transactionId]) REFERENCES [tblTransactionDetail]([transactionId]), 
    CONSTRAINT [FK_mstLandDetail_ToTable_5] FOREIGN KEY ([streetNameId]) REFERENCES [mstStreetName]([streetNameId]), 
    CONSTRAINT [FK_mstLandDetail_ToTable_6] FOREIGN KEY ([propertyTypeId]) REFERENCES [enumPropertyType]([propertyTypeId]), 
    
		
)
