CREATE TABLE [dbo].[mstTaxPayerProfile]
(
	[taxPayerId] INT NOT NULL PRIMARY KEY IDENTITY,	
	[taxPayerTypeId] [int] NOT NULL,
	[vendorTypeId] [int] NULL,
	[ttin] [varchar](10) NOT NULL,
	[cid] [varchar](50) NOT NULL,
	[tpn] [varchar](150) NULL,
	[titleId] [int] NOT NULL,
	[firstName] [varchar](250) NOT NULL,
	[middleName] [varchar](245) NULL,
	[lastName] [varchar](250) NULL,
	[dob] [date] NOT NULL,
	[genderId] [int] NOT NULL,
	[pVillageId] [int] NOT NULL,
	[cDzongkhagId] [int] NULL,
	[cAddress] [varchar](300) NULL,
	[occupationId] [int] NOT NULL,
	[workingAgency] [varchar](345) NULL,
	[phoneNo] [varchar](45) NULL,
	[mobileNo] [varchar](50) NULL,
	[email] VARCHAR(250) NULL,	
	[fax] [varchar](150) NULL,
	[contactPerson] [varchar](250) NULL,
	[bankAccountNo] [varchar](145) NULL,
	[bankBranchId] [int] NULL,	
	[taxSMSSentYearId] [int] NULL,
	[censusSMSsentYrId] [int] NULL,
	[isActive] [bit] NOT NULL,	
	[createdOn] [date] NOT NULL,
	[createdBy] [int] NOT NULL,
	[modifiedDate] [date] NULL,
	[modifiedBy] [int] NULL, 
    CONSTRAINT [FK_mstTaxPayer_ToTable] FOREIGN KEY ([taxPayerTypeId]) REFERENCES [enumTaxPayerType]([taxPayerTypeId]), 
    CONSTRAINT [FK_mstTaxPayer_ToTable_1] FOREIGN KEY ([pVillageId]) REFERENCES [mstVillage]([villageId]), 
    CONSTRAINT [FK_mstTaxPayer_ToTable_2] FOREIGN KEY ([cDzongkhagId]) REFERENCES [mstDzongkhag]([dzongkhagId]), 
    CONSTRAINT [FK_mstTaxPayer_ToTable_3] FOREIGN KEY ([occupationId]) REFERENCES [mstOccupation]([occupationId]), 
    CONSTRAINT [FK_mstTaxPayer_ToTable_4] FOREIGN KEY ([genderId]) REFERENCES [enumGender]([genderId]), 
    CONSTRAINT [FK_mstTaxPayer_ToTable_5] FOREIGN KEY ([bankBranchId]) REFERENCES [mstBankBranch]([bankBranchId]), 
    CONSTRAINT [FK_mstTaxPayer_ToTable_6] FOREIGN KEY ([titleId]) REFERENCES [enumTitle]([titleId]), 
    CONSTRAINT [FK_mstTaxPayer_ToTable_7] FOREIGN KEY ([taxSMSSentYearId]) REFERENCES [mstCalendarYear]([calendarYearId]), 
    CONSTRAINT [FK_mstTaxPayer_ToTable_8] FOREIGN KEY ([censusSMSsentYrId]) REFERENCES [mstCalendarYear]([calendarYearId]), 
    CONSTRAINT [FK_mstTaxPayerProfile_ToTable] FOREIGN KEY ([vendorTypeId]) REFERENCES [enumVendorType]([vendorTypeId]),
	
)
