CREATE TABLE [dbo].[mstWaterConnection]
(
	[waterConnectionId] INT NOT NULL PRIMARY KEY IDENTITY,
	[landDetailId] [int] NOT NULL,
	 [landOwnershipId] INT NOT NULL, 
	[waterConnectionStatusId] [int] NOT NULL,
	[ownerTypeId] [int] NOT NULL,
	[changeTypeId] [smallint] NULL,
	[waterMeterNo] [varchar](145) NOT NULL,
	[waterMeterTypeId] [int] NOT NULL,
	[consumerNo] [varchar](145) NOT NULL,
	[connectionDate] [date] NOT NULL,
	[sewerageConnection] BIT NOT NULL,
	[solidWaste] BIT NOT NULL, 
	[waterConnectionTypeId] [int] NOT NULL,
	[waterLineTypeId] [int] NOT NULL,
	[standardConsumption] INT NOT NULL,
	[createdBy] [int] NOT NULL,
	[createdOn] [date] NOT NULL,
	[modifiedBy] [int] NULL,
	[modifiedOn] [date] NULL,
	[billingAddress] [varchar](100) NOT NULL,
	[zoneId] [int] NOT NULL,
	[flatNo] [varchar](45) NULL,
	[initialReading] [decimal](10, 2) NOT NULL,
	[organisationName] [varchar](450) NULL,
	[isActive] BIT NOT NULL,
	[isPermanentConnection] BIT NULL, 
	[remarks] [varchar](450) NULL,
	[isPermanentDisconnect] BIT NULL,
	[disconnectDate] [date] NULL,
	[noOfUnits] [int] NOT NULL DEFAULT 1,	
	[reconnectionDate] [date] NULL,
	[sewarageConnectionDate] [date] NULL,
	[sewarageConnectedBy] [int] NULL,
	[primaryMobileNo] [varchar](8) NOT NULL,
	[secondaryMobileNo] [varchar](8) NULL, 
    [transactionId] BIGINT NULL, 
   
    [maxReadingDate] DATE NULL, 
   
    CONSTRAINT [FK_mstWaterConnection_ToTable] FOREIGN KEY ([landDetailId]) REFERENCES [mstLandDetail]([landDetailId]), 
    CONSTRAINT [FK_mstWaterConnection_ToTable_1] FOREIGN KEY ([waterMeterTypeId]) REFERENCES [mstWaterMeterType]([waterMeterTypeId]), 
    CONSTRAINT [FK_mstWaterConnection_ToTable_2] FOREIGN KEY ([waterConnectionStatusId]) REFERENCES [enumWaterConnectionStatus]([waterConnectionStatusId]), 
    CONSTRAINT [FK_mstWaterConnection_ToTable_3] FOREIGN KEY ([waterConnectionTypeId]) REFERENCES [mstWaterConnectionType]([waterConnectionTypeId]), 
    CONSTRAINT [FK_mstWaterConnection_ToTable_4] FOREIGN KEY ([waterLineTypeId]) REFERENCES [mstWaterLineType]([waterLineTypeId]), 
    CONSTRAINT [FK_mstWaterConnection_ToTable_5] FOREIGN KEY ([zoneId]) REFERENCES [mstZone]([zoneId]), 
    CONSTRAINT [FK_mstWaterConnection_ToTable_6] FOREIGN KEY ([ownerTypeId]) REFERENCES [enumOwnerType]([ownerTypeId]), 
    CONSTRAINT [FK_mstWaterConnection_ToTable_7] FOREIGN KEY ([landOwnershipId]) REFERENCES [tblLandOwnershipDetail]([landOwnershipId]),
 

)
