CREATE TABLE [dbo].[tblBfsTransactiondetails]
(
	[bfsTransactionDetailId] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[bfs_msgType] [varchar](200) NULL,
	[bfs_benfId] [varchar](200) NULL,
	[bfs_orderNo] [varchar](200) NULL,
	[bfs_benfBankCode] [varchar](200) NULL,
	[bfs_txnCurrency] [varchar](230) NULL,
	[bfs_txnAmount] [decimal](18, 2) NULL,
	[bfs_remitterEmail] [varchar](250) NULL,
	[bfs_paymentDesc] [varchar](250) NULL,
	[bfs_version] [varchar](230) NULL,
	[bfs_benfTxnTime] [varchar](200) NULL,
	[bfs_checksum] [varchar](1000) NULL,
	[bfs_responseChecksum] VARCHAR(1000) NULL,
	[bfs_bfsTxnId] [varchar](200) NULL,
	[bfs_remitterBankId] [varchar](240) NULL,
	[bfs_remitterAccNo] [varchar](220) NULL,
	[bfs_remitterOtp] [varchar](250) NULL,
	[bfs_debitAuthCode] [varchar](220) NULL,
	[bfs_debitAuthNo] [varchar](100) NULL,
	[bfs_responseDesc] [varchar](150) NULL,
	[bfs_responseCode] [varchar](MAX) NULL,
	[bfs_bankId] [varchar](150) NULL,
	[bfs_bankName] [varchar](150) NULL,
	[bfs_remitterName] [varchar](250) NULL,
	[bfs_txnTime] [varchar](100) NULL,
	[bfs_statusState] [varchar](250) NULL,
	[createdOn] [datetime] NULL,
	[createdBy] INT NULL, 
    [demandIds] VARCHAR(MAX) NULL 
)
