CREATE TABLE [dbo].[tblECdetail]
(
	[ecDetailId] INT NOT NULL PRIMARY KEY IDENTITY,	
	[applicantId] [int] NOT NULL,
	[ecActivityTypeId] [int] NOT NULL,
	[industryTypeId] [int] NOT NULL,
	[quantity] [decimal](10, 2) NOT NULL,
	[projectName] [varchar](300) NOT NULL,
	[startDate] [date] NOT NULL,
	[endDate] [date] NOT NULL,
	[projectStatusId] INT NULL,
	[projectClosedBy] [int] NULL,
	[projectCloseDate] DATE NULL,
	[projectCloseRemarks] [varchar](300) NULL,
	[approvalStatusId] INT NULL,
	[approvalRemarks] [varchar](300) NULL,
	[approvalOn] [date] NULL,
	[approvedBy] [int] NULL,
	[initialAmount] [decimal](18, 2) NOT NULL,
	[createdBy] [int] NOT NULL,
	[createdOn] DATETIME NOT NULL,
	[modifiedOn] DATETIME NULL,
	[modifiedBy] [int] NULL, 
    CONSTRAINT [FK_tblECdetail_ToTable] FOREIGN KEY ([applicantId]) REFERENCES [mstECApplicantdetail]([applicantId]), 
    CONSTRAINT [FK_tblECdetail_ToTable_1] FOREIGN KEY ([ecActivityTypeId]) REFERENCES [mstECActivityType]([ecActivityTypeId]), 
    CONSTRAINT [FK_tblECdetail_ToTable_2] FOREIGN KEY ([industryTypeId]) REFERENCES [enumIndustryType]([industryTypeId]), 
    CONSTRAINT [FK_tblECdetail_ToTable_3] FOREIGN KEY ([projectStatusId]) REFERENCES [enumProjectStatus]([projectStatusId]), 
    CONSTRAINT [FK_tblECdetail_ToTable_4] FOREIGN KEY ([approvalStatusId]) REFERENCES [enumApprovalStatus]([approvalStatusId]),
)
