CREATE TABLE [dbo].[tblLandLease]
(
	[landLeaseId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [landDetailId] INT NOT NULL, 
    [taxPayerId] INT NOT NULL, 
    [billingScheduleId] INT NOT NULL,  
    [leaseTypeId] INT NOT NULL, 
    [leaseActivityTypeId] INT NOT NULL,     
    [hasShed] BIT NOT NULL, 
    [hassecurityDeposit] BIT NOT NULL, 
    [startDate] DATE NOT NULL, 
    [leaseAmount] DECIMAL(18, 2) NOT NULL, 
    [shedAmount] DECIMAL(18, 2) NOT NULL, 
    [remarks] VARCHAR(350) NULL,
	[isActive] BIT NOT NULL, 
    [terminateDate] DATE NULL, 
    [terminateReason] VARCHAR(250) NULL, 
    [createdBy] INT NOT NULL, 
    [createdOn] DATETIME NOT NULL, 
    [modifiedBy] INT NULL, 
    [modifiedOn] DATETIME NULL, 
    [leaseApprovalNo] VARCHAR(300) NULL, 
    CONSTRAINT [FK_tblLandLease_ToTable] FOREIGN KEY ([billingScheduleId]) REFERENCES [enumBillingSchedule]([billingScheduleId]), 
    CONSTRAINT [FK_tblLandLease_ToTable_1] FOREIGN KEY ([landDetailId]) REFERENCES [mstLandDetail]([landDetailId]), 
    CONSTRAINT [FK_tblLandLease_ToTable_2] FOREIGN KEY ([taxPayerId]) REFERENCES [mstTaxPayerProfile]([taxPayerId]), 
    CONSTRAINT [FK_tblLandLease_ToTable_3] FOREIGN KEY ([leaseTypeId]) REFERENCES [enumLeaseType]([leaseTypeId]), 
    CONSTRAINT [FK_tblLandLease_ToTable_4] FOREIGN KEY ([leaseActivityTypeId]) REFERENCES [enumLeaseActivityType]([leaseActivityTypeId]), 
    --CONSTRAINT [FK_tblLandLease_ToTable_5] FOREIGN KEY ([taxPeriodId]) REFERENCES [mstTaxPeriod]([taxPeriodId]),
)
