CREATE TABLE [dbo].[trnWaterConnection]
(
	[trnWaterConnectionId] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[landDetailId] [int] NOT NULL,
	[waterConnectionStatusId] [int] NOT NULL,
	[waterMeterNo] [varchar](145) NOT NULL,
	[waterMeterTypeId] [int] NOT NULL,
	[consumerNo] [varchar](145) NOT NULL,
	[applicationDate] [date] NOT NULL,
	[sewerageConnection] BIT NOT NULL,
	[waterConnectionTypeId] [int] NOT NULL,
	[waterLineTypeId] [int] NOT NULL,
	[standardCosumption] INT NOT NULL,
	[createdBy] [int] NOT NULL,
	[createdOn] [date] NOT NULL,
	[modifiedBy] [int] NULL,
	[modifiedOn] [date] NULL,
	[billingAddress] [varchar](100) NOT NULL,
	[zoneId] [int] NOT NULL,
	[flatNo] [varchar](45) NULL,
	[initialReading] [decimal](10, 2) NOT NULL,
	[organisationName] [varchar](450) NULL,
	[isActive] BIT NOT NULL,
	[remarks] [varchar](450) NULL,
	[reUse] BIT NULL,
	[disconnectDate] [date] NULL,
	[noOfUnits] [int] NOT NULL DEFAULT 1,
	[ownerTypeId] [int] NOT NULL,
	[changeTypeId] [smallint] NULL,
	[reconnectionDate] [date] NULL,
	[sewarageConnectionDate] [date] NULL,
	[sewarageConnectedBy] [int] NULL,
	[primaryMobileNo] [varchar](8) NOT NULL,
	[secondaryMobileNo] [varchar](8) NULL, 
    [workLevelId] INT NOT NULL, 
    [transactionId] BIGINT NOT NULL, 
	[isPermanentDisconnect] BIT NULL, 
    [approvalStatusId] BIT NULL , 
    [landOwnershipId] INT NULL, 
	 [g2cApplicationNo] VARCHAR(300) NULL, 
    [readingDate] DATE NULL, 
    [previousReadingDate] DATE NULL, 
    [previousReading] INT NULL, 
    [oldWaterConnectionId] INT NULL, 
    [isPermanent] BIT NULL, 
    CONSTRAINT [FK_trnWaterConnection_ToTable] FOREIGN KEY ([landDetailId]) REFERENCES [mstLandDetail]([landDetailId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_1] FOREIGN KEY ([waterMeterTypeId]) REFERENCES [mstWaterMeterType]([waterMeterTypeId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_2] FOREIGN KEY ([waterConnectionStatusId]) REFERENCES [enumWaterConnectionStatus]([waterConnectionStatusId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_3] FOREIGN KEY ([waterConnectionTypeId]) REFERENCES [mstWaterConnectionType]([waterConnectionTypeId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_4] FOREIGN KEY ([waterLineTypeId]) REFERENCES [mstWaterLineType]([waterLineTypeId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_5] FOREIGN KEY ([zoneId]) REFERENCES [mstZone]([zoneId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_6] FOREIGN KEY ([ownerTypeId]) REFERENCES [enumOwnerType]([ownerTypeId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_7] FOREIGN KEY ([workLevelId]) REFERENCES [enumWorkLevel]([workLevelId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_8] FOREIGN KEY ([transactionId]) REFERENCES [tblTransactionDetail]([transactionId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_9] FOREIGN KEY ([landOwnershipId]) REFERENCES [tblLandOwnershipDetail]([landOwnershipId]), 
    CONSTRAINT [FK_trnWaterConnection_ToTable_10] FOREIGN KEY ([oldWaterConnectionId]) REFERENCES [mstWaterConnection]([waterConnectionId]),
 

)
