CREATE TABLE [dbo].[trnTaxPayerInformation]
(
	[trnTaxpayerId] INT NOT NULL PRIMARY KEY IDENTITY,   
	[taxPayerTypeId] [int] NOT NULL,
	[ttin] [varchar](10) NOT NULL,
	[cid] [varchar](50) NOT NULL,
	[tpn] [varchar](150) NULL,
	[titleId] [int] NULL,
	[firstName] [varchar](250) NOT NULL,
	[middleName] [varchar](245) NULL,
	[lastName] [varchar](250) NULL,
	[dob] [date] NOT NULL,
	[genderId] [int] NOT NULL,
	[pVillageId] [int] NOT NULL,
	[cDzongkhagId] [int] NULL,
	[cAddress] [varchar](300) NULL,
	[occupationId] [int] NOT NULL,
	[workingAgency] [varchar](345) NULL,
	[phoneNo] [varchar](45) NULL,
	[mobileNo] [varchar](50) NULL,
	[email] VARCHAR(250) NULL,	
	[organizationName] [varchar](350) NULL,
	[orgPhone] [varchar](150) NULL,
	[fax] [varchar](150) NULL,
	[orgEmail] [varchar](250) NULL,
	[contactPerson] [varchar](250) NULL,
	[bankAccountNo] [varchar](145) NULL,
	[bankBranchId] [int] NULL,	
	[eSakorTransactionId] VARCHAR(250) NULL,	
    [transactorTypeId] INT NULL,
	[landTransferTypeId] INT NOT NULL ,
	[isActive] [bit] NOT NULL,	
	[createdOn] [date] NOT NULL,
	[createdBy] [int] NOT NULL,
	[modifiedDate] [date] NULL,
	[modifiedBy] [int] NULL,  
    CONSTRAINT [FK_trnTaxPayerInformation_ToTable] FOREIGN KEY ([taxPayerTypeId]) REFERENCES [enumTaxPayerType]([taxPayerTypeId]), 
    CONSTRAINT [FK_trnTaxPayerInformation_ToTable_1] FOREIGN KEY ([pVillageId]) REFERENCES [mstVillage]([villageId]), 
    CONSTRAINT [FK_trnTaxPayerInformation_ToTable_2] FOREIGN KEY ([cDzongkhagId]) REFERENCES [mstDzongkhag]([dzongkhagId]), 
    CONSTRAINT [FK_trnTaxPayerInformation_ToTable_3] FOREIGN KEY ([occupationId]) REFERENCES [mstOccupation]([occupationId]), 
    CONSTRAINT [FK_trnTaxPayerInformation_ToTable_4] FOREIGN KEY ([genderId]) REFERENCES [enumGender]([genderId]), 
    CONSTRAINT [FK_trnTaxPayerInformation_ToTable_5] FOREIGN KEY ([bankBranchId]) REFERENCES [mstBankBranch]([bankBranchId]), 
    CONSTRAINT [FK_trnTaxPayerInformation_ToTable_6] FOREIGN KEY ([titleId]) REFERENCES [enumTitle]([titleId]), 
	CONSTRAINT [FK_trnTaxPayerInformation_ToTable_7] FOREIGN KEY ([transactorTypeId]) REFERENCES [enumTransactorType]([transactorTypeId]),
	 CONSTRAINT[FK_trnTaxPayerInformation_ToTable_8] FOREIGN KEY ([landTransferTypeId]) REFERENCES [enumLandTransferType]([landTransferTypeId]), 

   )
