/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key a9d42fd9-5db3-4ef7-a525-c6afbf3fc28c is skipped, element [dbo].[tblComplain].[Id] (SqlSimpleColumn) will not be renamed to complainId';


GO
PRINT N'Rename refactoring operation with key 649121fd-ef2c-48d0-a8c3-290d8ff5617d is skipped, element [dbo].[tblComplain].[dateline] (SqlSimpleColumn) will not be renamed to deadLine ';


GO
PRINT N'Rename refactoring operation with key c45229e1-f6fa-436a-a3d6-b00bb785bcd5 is skipped, element [dbo].[enumComplainType].[Id] (SqlSimpleColumn) will not be renamed to complainTypeId';


GO
PRINT N'Rename refactoring operation with key 4ff8a3c4-dd23-4498-92b9-a832fb7e34e2 is skipped, element [dbo].[enumComplainType].[ComplainType] (SqlSimpleColumn) will not be renamed to complainType';


GO
PRINT N'Rename refactoring operation with key 2c7c6c20-1c58-4c20-a266-c030e421918f is skipped, element [dbo].[enumComplainStatusId].[Id] (SqlSimpleColumn) will not be renamed to complainStatusId';


GO
PRINT N'Creating Table [dbo].[enumComplainStatusId]...';


GO
CREATE TABLE [dbo].[enumComplainStatusId] (
    [complainStatusId] INT           IDENTITY (1, 1) NOT NULL,
    [complainStatus]   VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([complainStatusId] ASC)
);


GO
PRINT N'Creating Table [dbo].[enumComplainType]...';


GO
CREATE TABLE [dbo].[enumComplainType] (
    [complainTypeId] INT           IDENTITY (1, 1) NOT NULL,
    [complainType]   VARCHAR (150) NOT NULL,
    PRIMARY KEY CLUSTERED ([complainTypeId] ASC)
);


GO
PRINT N'Creating Table [dbo].[tblComplain]...';


GO
CREATE TABLE [dbo].[tblComplain] (
    [complainId]        INT           IDENTITY (1, 1) NOT NULL,
    [waterConnectionId] INT           NOT NULL,
    [complainTypeId]    INT           NOT NULL,
    [complainStatusId]  INT           NOT NULL,
    [instruction]       VARCHAR (350) NOT NULL,
    [deadLine ]         DATETIME      NOT NULL,
    [createdOn]         DATE          NOT NULL,
    [createdBy]         INT           NOT NULL,
    [modifiedOn]        DATETIME2 (0) NULL,
    [modifiedBy]        INT           NULL,
    PRIMARY KEY CLUSTERED ([complainId] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblComplain_ToTable]...';


GO
ALTER TABLE [dbo].[tblComplain] WITH NOCHECK
    ADD CONSTRAINT [FK_tblComplain_ToTable] FOREIGN KEY ([complainTypeId]) REFERENCES [dbo].[enumComplainType] ([complainTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblComplain_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblComplain] WITH NOCHECK
    ADD CONSTRAINT [FK_tblComplain_ToTable_1] FOREIGN KEY ([complainStatusId]) REFERENCES [dbo].[enumComplainStatusId] ([complainStatusId]);


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'a9d42fd9-5db3-4ef7-a525-c6afbf3fc28c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('a9d42fd9-5db3-4ef7-a525-c6afbf3fc28c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '649121fd-ef2c-48d0-a8c3-290d8ff5617d')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('649121fd-ef2c-48d0-a8c3-290d8ff5617d')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'c45229e1-f6fa-436a-a3d6-b00bb785bcd5')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('c45229e1-f6fa-436a-a3d6-b00bb785bcd5')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '4ff8a3c4-dd23-4498-92b9-a832fb7e34e2')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('4ff8a3c4-dd23-4498-92b9-a832fb7e34e2')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '2c7c6c20-1c58-4c20-a266-c030e421918f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('2c7c6c20-1c58-4c20-a266-c030e421918f')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[tblComplain] WITH CHECK CHECK CONSTRAINT [FK_tblComplain_ToTable];

ALTER TABLE [dbo].[tblComplain] WITH CHECK CHECK CONSTRAINT [FK_tblComplain_ToTable_1];


GO
PRINT N'Update complete.';


GO
