CREATE TABLE [dbo].[mstBuildingDetail]
(
	[buildingDetailId] INT NOT NULL PRIMARY KEY IDENTITY,
    [landDetailId] int NOT NULL,
    [buildingClassId] int DEFAULT '1' NOT NULL,
    [storyTypeId] INT NOT NULL , 
    [buildingNo] varchar(250) DEFAULT NULL,
    [buildupArea] decimal(10,2) NOT NULL,
    [plinthArea] DECIMAL(18, 2) NULL,
    [noOfUnits] int NOT NULL,
  [numberOfFloors] int NOT NULL,  
  [garbagServiceAccessibilityId] int DEFAULT NULL,
  [streetLightAccessibilityId] int DEFAULT NULL,
  [occupancyCertificateNo] varchar(256) DEFAULT NULL,
  [constructionTypeId] int NOT NULL,
  [yearOfConstruction] int DEFAULT NULL,
  [occupancyCertificateIssued] bit DEFAULT NULL NULL,
  [occupancyCertificateIssueDate] date DEFAULT NULL,
  [paymentCompletionStatusId] BIT NOT NULL DEFAULT '0',  
  [waterConnection] bit DEFAULT NULL,
  [sewerageConnection] bit DEFAULT NULL,
  [attic] bit DEFAULT NULL,
  [structureCategoryId] int DEFAULT NULL,
  [structureTypeId] int DEFAULT NULL,
  [materialTypeId] int DEFAULT NULL,
  [archFeature] bit DEFAULT NULL,
  [roofing] bit DEFAULT NULL,
  [roofingTypeId] int DEFAULT NULL NULL,
   [traditionalPainting] bit DEFAULT NULL NULL,
  [buildingColourId] int DEFAULT NULL,
  [boundaryTypeId] int DEFAULT NULL, 
  [plantation] bit DEFAULT NULL,
  [waterTankLocationId] int DEFAULT NULL,
  [numberDisplayed] bit DEFAULT NULL,
  [parkingSlotId] int DEFAULT NULL,
  [fireExtingusher] bit DEFAULT NULL,
  [waterSupplyAccessibilityId] int DEFAULT NULL,  
  [roadAccess] bit DEFAULT NULL,
  [drainToStormWaterDrain] bit DEFAULT NULL, 
  [dateOfFinalInspection] date DEFAULT NULL,
  [occupancyAlteredOn] date DEFAULT NULL,
  [occupancyAlteredBy] int DEFAULT NULL,
  [occupancyReferenceId] int DEFAULT NULL,
  [advanceInfoFedBy] int DEFAULT NULL,
  [advanceInfoInfoFedOn] date DEFAULT NULL,
  [remarks] varchar(345) DEFAULT NULL, 
  [modificationRemarks] varchar(300) DEFAULT NULL,
  [modificationReasonId] int DEFAULT NULL,
  [transactionId] int DEFAULT NULL,
  [createG2cApplicationNo] VARCHAR(150) NULL, 
  [UpdateG2cApplicationNo] VARCHAR(150) NULL, 
  [createdBy] int NOT NULL,
  [createdOn] datetime  NOT NULL,
  [modifiedBy] int DEFAULT NULL,
  [modifiedOn] datetime DEFAULT NULL,  
    CONSTRAINT [FK_mstBuildingDetail_ToTable] FOREIGN KEY ([landDetailId]) REFERENCES [mstLandDetail]([landDetailId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_1] FOREIGN KEY ([constructionTypeId]) REFERENCES [mstConstructionType]([constructionTypeId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_2] FOREIGN KEY ([structureCategoryId]) REFERENCES [mstStructureCategory]([structureCategoryId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_3] FOREIGN KEY ([structureTypeId]) REFERENCES [mstStructureType]([structureTypeId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_4] FOREIGN KEY ([materialTypeId]) REFERENCES [mstMaterialType]([materialTypeId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_5] FOREIGN KEY ([roofingTypeId]) REFERENCES [mstRoofingType]([roofingTypeId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_6] FOREIGN KEY ([buildingColourId]) REFERENCES [mstBuildingColour]([buildingColourId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_7] FOREIGN KEY ([boundaryTypeId]) REFERENCES [mstBoundaryType]([boundaryTypeId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_8] FOREIGN KEY ([waterTankLocationId]) REFERENCES [enumWaterTankLocation]([waterTankLocationId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_9] FOREIGN KEY ([parkingSlotId]) REFERENCES [mstParkingSlot]([parkingSlotId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_10] FOREIGN KEY ([waterSupplyAccessibilityId]) REFERENCES [enumServiceAccessibilityType]([serviceAccessibilityId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_11] FOREIGN KEY ([garbagServiceAccessibilityId]) REFERENCES [enumServiceAccessibilityType]([serviceAccessibilityId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_12] FOREIGN KEY ([streetLightAccessibilityId]) REFERENCES [enumServiceAccessibilityType]([serviceAccessibilityId]), 
    CONSTRAINT [FK_mstBuildingDetail_ToTable_13] FOREIGN KEY ([storyTypeId]) REFERENCES [enumStoryType]([storyTypeId]),
  )

GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'who entered advance info/userid',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'mstBuildingDetail',
    @level2type = N'COLUMN',
    @level2name = N'advanceInfoFedBy'