/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering Procedure [dbo].[rptGetTaxRates]...';


GO
ALTER PROCEDURE [dbo].[rptGetTaxRates]
	@TransactionTypeId int
AS
--	EXEC [dbo].[rptGetTaxRates] 19

   select * 
   
   from mstRate r 
   join mstTaxMaster t on r.taxId=t.taxId
   join mstSlab s on r.slabId=s.slabId
   left join mstTransactionTypeTaxMap ty on t.taxId=ty.taxId
   left join mstLandUseSubCategory sc on s.landUseSubCategoryId=sc.landUseSubCategoryId
   where ty.transactionTypeId=@TransactionTypeId
RETURN 0
GO
PRINT N'Creating Procedure [dbo].[spCollectionByFromDateToDate]...';


GO
CREATE PROCEDURE [dbo].[spCollectionByFromDateToDate]
	@FromDate Date,
	@ToDate Date
AS
	  SELECT  ROW_NUMBER() OVER(
       ORDER BY (select 1)) AS Sl,* from(
select 'Cash' as PaymentMode,'-' as PaymentModeNo,'' as PaymentModeDate, sum(amount) as Amount from tblPaymentLeger where paymentModeId = 1 and createdOn>=@FromDate and createdOn<=@ToDate
group by paymentModeId
union all
select pm.paymentMode as PaymentMode, pl.paymentModeNo as PaymentModeNo,pl.paymentModeDate as PaymentModeDate, amount as Amount from tblPaymentLeger pl
left join [dbo].[enumPaymentMode] pm on pl.paymentModeId = pm.paymentModeId

where pl.paymentModeId = 2 and pl.createdOn>=@FromDate and pl.createdOn<=@ToDate) t    
RETURN 0
GO
PRINT N'Update complete.';


GO
