CREATE TABLE [dbo].[mstBuildingUnitDetail]
(
  [buildingUnitDetailId] INT NOT NULL PRIMARY KEY IDENTITY,
  [buildingDetailId] int NOT NULL,
  [buildingUnitClassId] int DEFAULT NULL NOT NULL,
  [floorNameId] int DEFAULT NULL NOT NULL,
  [buildingUnitUseTypeId] int DEFAULT NULL NOT NULL,
   [isRegularized] bit  NOT NULL,
  [floorNo] varchar(45) DEFAULT NULL NOT NULL,
  [flatNo] varchar(50) DEFAULT NULL NOT NULL,
  [noOfUnit] int DEFAULT '1' NOT NULL,  
  [floorArea] decimal(10,2) DEFAULT NULL NOT NULL,
  [noOfrooms] int DEFAULT NULL NOT NULL,
  [taxPayerId] int DEFAULT NULL NOT NULL,
  	[landDetailId] INT NOT NULL ,
  [unitOwnerTypeId] int DEFAULT NULL NOT NULL,
  [isMainOwner] bit DEFAULT NULL NOT NULL,
  [createdBy] int DEFAULT NULL,
  [createdOn] date DEFAULT NULL,
  [modifiedBy] int DEFAULT NULL,
  [modifiedOn] date DEFAULT NULL,
  [transferStatusId] tinyint DEFAULT NULL,
    [isActive] BIT NOT NULL DEFAULT 1, 
    [createG2cApplicationNo] VARCHAR(150) NULL, 
    [updateG2cApplicationNo] VARCHAR(150) NULL, 
    [hasIssue] BIT NOT NULL DEFAULT 0, 
    [remarks] VARCHAR(300) NULL, 
    CONSTRAINT [FK_mstBuildingUnitDetail_ToTable] FOREIGN KEY ([buildingDetailId]) REFERENCES [mstBuildingDetail]([buildingDetailId]), 
    CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_1] FOREIGN KEY ([buildingUnitUseTypeId]) REFERENCES [mstBuildingUnitUseType]([buildingUnitUseTypeId]), 
    CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_2] FOREIGN KEY ([floorNameId]) REFERENCES [mstFloorName]([floorNameId]), 
    CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_3] FOREIGN KEY ([buildingUnitClassId]) REFERENCES [mstBuildingUnitClass]([buildingUnitClassId]), 
    CONSTRAINT [FK_mstBuildingUnitDetail_ToTable_4] FOREIGN KEY ([unitOwnerTypeId]) REFERENCES [enumUnitOwnerType]([unitOwnerTypeId]),
)
