
CREATE TABLE [dbo].[enumGender](
	[genderId] [int] IDENTITY(1,1) NOT NULL,
	[Gender] [varchar](45) NOT NULL,
 CONSTRAINT [PK_enumgender_ID] PRIMARY KEY CLUSTERED 
(
	[genderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO