/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [dbo].[mstTaxPayerProfile].[orgEmail] is being dropped, data loss could occur.

The column [dbo].[mstTaxPayerProfile].[orgPhone] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[mstTaxPayerProfile])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Rename refactoring operation with key 5ef9fb8c-7dc2-488a-aadf-b259719f96d7, 950b5433-210e-4057-8f4b-8cae8335da6e is skipped, element [dbo].[enumVendorType].[Id] (SqlSimpleColumn) will not be renamed to vendorTypeId';


GO
PRINT N'Rename refactoring operation with key cf147fd4-9d63-4102-8b03-2b0655c7ae5c is skipped, element [dbo].[enumVendorType].[VendorType] (SqlSimpleColumn) will not be renamed to vendorType';


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblHouseAllocation_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblHouseAllocation] DROP CONSTRAINT [FK_tblHouseAllocation_ToTable_1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblLandLease_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblLandLease] DROP CONSTRAINT [FK_tblLandLease_ToTable_2];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_3]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] DROP CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_3];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblParkingfeeDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblParkingfeeDetail] DROP CONSTRAINT [FK_tblParkingfeeDetail_ToTable_2];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblStallAllocation_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblStallAllocation] DROP CONSTRAINT [FK_tblStallAllocation_ToTable_1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstTaxPayer_ToTable]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] DROP CONSTRAINT [FK_mstTaxPayer_ToTable];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstTaxPayer_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] DROP CONSTRAINT [FK_mstTaxPayer_ToTable_3];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstTaxPayer_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] DROP CONSTRAINT [FK_mstTaxPayer_ToTable_4];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstTaxPayer_ToTable_5]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] DROP CONSTRAINT [FK_mstTaxPayer_ToTable_5];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstTaxPayer_ToTable_6]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] DROP CONSTRAINT [FK_mstTaxPayer_ToTable_6];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstTaxPayer_ToTable_7]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] DROP CONSTRAINT [FK_mstTaxPayer_ToTable_7];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstTaxPayer_ToTable_8]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] DROP CONSTRAINT [FK_mstTaxPayer_ToTable_8];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstTaxPayer_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] DROP CONSTRAINT [FK_mstTaxPayer_ToTable_2];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_mstTaxPayer_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] DROP CONSTRAINT [FK_mstTaxPayer_ToTable_1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_trnLandTransferDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[trnLandTransferDetail] DROP CONSTRAINT [FK_trnLandTransferDetail_ToTable_2];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblLandOwnershipDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblLandOwnershipDetail] DROP CONSTRAINT [FK_tblLandOwnershipDetail_ToTable_2];


GO
PRINT N'Starting rebuilding table [dbo].[mstTaxPayerProfile]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_mstTaxPayerProfile] (
    [taxPayerId]        INT           IDENTITY (1, 1) NOT NULL,
    [taxPayerTypeId]    INT           NOT NULL,
    [vendorTypeId]      INT           NULL,
    [ttin]              VARCHAR (10)  NOT NULL,
    [cid]               VARCHAR (50)  NOT NULL,
    [tpn]               VARCHAR (150) NULL,
    [titleId]           INT           NOT NULL,
    [firstName]         VARCHAR (250) NOT NULL,
    [middleName]        VARCHAR (245) NULL,
    [lastName]          VARCHAR (250) NULL,
    [dob]               DATE          NOT NULL,
    [genderId]          INT           NOT NULL,
    [pVillageId]        INT           NOT NULL,
    [cDzongkhagId]      INT           NULL,
    [cAddress]          VARCHAR (300) NULL,
    [occupationId]      INT           NOT NULL,
    [workingAgency]     VARCHAR (345) NULL,
    [phoneNo]           VARCHAR (45)  NULL,
    [mobileNo]          VARCHAR (50)  NULL,
    [email]             VARCHAR (250) NULL,
    [fax]               VARCHAR (150) NULL,
    [contactPerson]     VARCHAR (250) NULL,
    [bankAccountNo]     VARCHAR (145) NULL,
    [bankBranchId]      INT           NULL,
    [taxSMSSentYearId]  INT           NULL,
    [censusSMSsentYrId] INT           NULL,
    [isActive]          BIT           NOT NULL,
    [createdOn]         DATE          NOT NULL,
    [createdBy]         INT           NOT NULL,
    [modifiedDate]      DATE          NULL,
    [modifiedBy]        INT           NULL,
    PRIMARY KEY CLUSTERED ([taxPayerId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[mstTaxPayerProfile])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstTaxPayerProfile] ON;
        INSERT INTO [dbo].[tmp_ms_xx_mstTaxPayerProfile] ([taxPayerId], [taxPayerTypeId], [ttin], [cid], [tpn], [titleId], [firstName], [middleName], [lastName], [dob], [genderId], [pVillageId], [cDzongkhagId], [cAddress], [occupationId], [workingAgency], [phoneNo], [mobileNo], [email], [fax], [contactPerson], [bankAccountNo], [bankBranchId], [taxSMSSentYearId], [censusSMSsentYrId], [isActive], [createdOn], [createdBy], [modifiedDate], [modifiedBy])
        SELECT   [taxPayerId],
                 [taxPayerTypeId],
                 [ttin],
                 [cid],
                 [tpn],
                 [titleId],
                 [firstName],
                 [middleName],
                 [lastName],
                 [dob],
                 [genderId],
                 [pVillageId],
                 [cDzongkhagId],
                 [cAddress],
                 [occupationId],
                 [workingAgency],
                 [phoneNo],
                 [mobileNo],
                 [email],
                 [fax],
                 [contactPerson],
                 [bankAccountNo],
                 [bankBranchId],
                 [taxSMSSentYearId],
                 [censusSMSsentYrId],
                 [isActive],
                 [createdOn],
                 [createdBy],
                 [modifiedDate],
                 [modifiedBy]
        FROM     [dbo].[mstTaxPayerProfile]
        ORDER BY [taxPayerId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_mstTaxPayerProfile] OFF;
    END

DROP TABLE [dbo].[mstTaxPayerProfile];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_mstTaxPayerProfile]', N'mstTaxPayerProfile';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Table [dbo].[enumVendorType]...';


GO
CREATE TABLE [dbo].[enumVendorType] (
    [vendorTypeId] INT          IDENTITY (1, 1) NOT NULL,
    [vendorType]   VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([vendorTypeId] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblHouseAllocation_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblHouseAllocation] WITH NOCHECK
    ADD CONSTRAINT [FK_tblHouseAllocation_ToTable_1] FOREIGN KEY ([taxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblLandLease_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblLandLease] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLandLease_ToTable_2] FOREIGN KEY ([taxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnOccupancyCertificateApplication_ToTable_3]...';


GO
ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH NOCHECK
    ADD CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_3] FOREIGN KEY ([taxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblParkingfeeDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblParkingfeeDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_tblParkingfeeDetail_ToTable_2] FOREIGN KEY ([taxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblStallAllocation_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblStallAllocation] WITH NOCHECK
    ADD CONSTRAINT [FK_tblStallAllocation_ToTable_1] FOREIGN KEY ([taxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayer_ToTable]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayer_ToTable] FOREIGN KEY ([taxPayerTypeId]) REFERENCES [dbo].[enumTaxPayerType] ([taxPayerTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayer_ToTable_3]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayer_ToTable_3] FOREIGN KEY ([occupationId]) REFERENCES [dbo].[mstOccupation] ([occupationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayer_ToTable_4]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayer_ToTable_4] FOREIGN KEY ([genderId]) REFERENCES [dbo].[enumGender] ([genderId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayer_ToTable_5]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayer_ToTable_5] FOREIGN KEY ([bankBranchId]) REFERENCES [dbo].[mstBankBranch] ([bankBranchId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayer_ToTable_6]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayer_ToTable_6] FOREIGN KEY ([titleId]) REFERENCES [dbo].[enumTitle] ([titleId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayer_ToTable_7]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayer_ToTable_7] FOREIGN KEY ([taxSMSSentYearId]) REFERENCES [dbo].[mstCalendarYear] ([calendarYearId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayer_ToTable_8]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayer_ToTable_8] FOREIGN KEY ([censusSMSsentYrId]) REFERENCES [dbo].[mstCalendarYear] ([calendarYearId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayer_ToTable_2]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayer_ToTable_2] FOREIGN KEY ([cDzongkhagId]) REFERENCES [dbo].[mstDzongkhag] ([dzongkhagId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayer_ToTable_1]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayer_ToTable_1] FOREIGN KEY ([pVillageId]) REFERENCES [dbo].[mstVillage] ([villageId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnLandTransferDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[trnLandTransferDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandTransferDetail_ToTable_2] FOREIGN KEY ([fromTaxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblLandOwnershipDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblLandOwnershipDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLandOwnershipDetail_ToTable_2] FOREIGN KEY ([taxPayerId]) REFERENCES [dbo].[mstTaxPayerProfile] ([taxPayerId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_mstTaxPayerProfile_ToTable]...';


GO
ALTER TABLE [dbo].[mstTaxPayerProfile] WITH NOCHECK
    ADD CONSTRAINT [FK_mstTaxPayerProfile_ToTable] FOREIGN KEY ([vendorTypeId]) REFERENCES [dbo].[enumVendorType] ([vendorTypeId]);


GO
PRINT N'Refreshing Procedure [dbo].[rptDefaulterPropertyList]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[rptDefaulterPropertyList]';


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5ef9fb8c-7dc2-488a-aadf-b259719f96d7')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5ef9fb8c-7dc2-488a-aadf-b259719f96d7')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'cf147fd4-9d63-4102-8b03-2b0655c7ae5c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('cf147fd4-9d63-4102-8b03-2b0655c7ae5c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '950b5433-210e-4057-8f4b-8cae8335da6e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('950b5433-210e-4057-8f4b-8cae8335da6e')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[tblHouseAllocation] WITH CHECK CHECK CONSTRAINT [FK_tblHouseAllocation_ToTable_1];

ALTER TABLE [dbo].[tblLandLease] WITH CHECK CHECK CONSTRAINT [FK_tblLandLease_ToTable_2];

ALTER TABLE [dbo].[trnOccupancyCertificateApplication] WITH CHECK CHECK CONSTRAINT [FK_trnOccupancyCertificateApplication_ToTable_3];

ALTER TABLE [dbo].[tblParkingfeeDetail] WITH CHECK CHECK CONSTRAINT [FK_tblParkingfeeDetail_ToTable_2];

ALTER TABLE [dbo].[tblStallAllocation] WITH CHECK CHECK CONSTRAINT [FK_tblStallAllocation_ToTable_1];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayer_ToTable];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayer_ToTable_3];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayer_ToTable_4];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayer_ToTable_5];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayer_ToTable_6];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayer_ToTable_7];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayer_ToTable_8];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayer_ToTable_2];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayer_ToTable_1];

ALTER TABLE [dbo].[trnLandTransferDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandTransferDetail_ToTable_2];

ALTER TABLE [dbo].[tblLandOwnershipDetail] WITH CHECK CHECK CONSTRAINT [FK_tblLandOwnershipDetail_ToTable_2];

ALTER TABLE [dbo].[mstTaxPayerProfile] WITH CHECK CHECK CONSTRAINT [FK_mstTaxPayerProfile_ToTable];


GO
PRINT N'Update complete.';


GO
