/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key ee3803d4-c323-4135-88c0-4fbe1ad23962 is skipped, element [dbo].[EnumMenuFor].[Id] (SqlSimpleColumn) will not be renamed to menuForId';


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_menu]...';


GO
ALTER TABLE [dbo].[tbl_menu] DROP CONSTRAINT [DF__tmp_ms_xx__order__0C06BB60];


GO
PRINT N'Creating [dbo].[EnumMenuFor]...';


GO
CREATE TABLE [dbo].[EnumMenuFor] (
    [menuForId] INT           IDENTITY (1, 1) NOT NULL,
    [menuFor]   VARCHAR (150) NOT NULL,
    PRIMARY KEY CLUSTERED ([menuForId] ASC)
);


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'ee3803d4-c323-4135-88c0-4fbe1ad23962')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('ee3803d4-c323-4135-88c0-4fbe1ad23962')

GO

GO
PRINT N'Update complete.';


GO
