/*
Deployment script for tt_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tt_db"
:setvar DefaultFilePrefix "tt_db"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [dbo].[trnWaterConnection].[completionStatus] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[trnWaterConnection])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Rename refactoring operation with key 9398d4c4-002c-4774-b842-9c7168922eaf is skipped, element [dbo].[trnLandFeeDetail].[Id] (SqlSimpleColumn) will not be renamed to landFeeDetailId';


GO
PRINT N'Rename refactoring operation with key 7222f21d-9518-470e-be38-2469a92cc7ac is skipped, element [dbo].[mstLandServiceType].[Id] (SqlSimpleColumn) will not be renamed to landServiceTypeId';


GO
PRINT N'Dropping Default Constraint unnamed constraint on [dbo].[trnWaterConnection]...';


GO
ALTER TABLE [dbo].[trnWaterConnection] DROP CONSTRAINT [DF__trnWaterC__compl__03B16C81];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblDemand_ToTable_10]...';


GO
ALTER TABLE [dbo].[tblDemand] DROP CONSTRAINT [FK_tblDemand_ToTable_10];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblLedger_ToTable_5]...';


GO
ALTER TABLE [dbo].[tblLedger] DROP CONSTRAINT [FK_tblLedger_ToTable_5];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblStallDetailDemand_ToTable_3]...';


GO
ALTER TABLE [dbo].[tblStallDetailDemand] DROP CONSTRAINT [FK_tblStallDetailDemand_ToTable_3];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblStallDetailDemand_ToTable]...';


GO
ALTER TABLE [dbo].[tblStallDetailDemand] DROP CONSTRAINT [FK_tblStallDetailDemand_ToTable];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblStallDetailDemand_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblStallDetailDemand] DROP CONSTRAINT [FK_tblStallDetailDemand_ToTable_1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tblStallDetailDemand_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblStallDetailDemand] DROP CONSTRAINT [FK_tblStallDetailDemand_ToTable_2];


GO
PRINT N'Altering Table [dbo].[trnWaterConnection]...';


GO
ALTER TABLE [dbo].[trnWaterConnection] DROP COLUMN [completionStatus];


GO
PRINT N'Starting rebuilding table [dbo].[tblStallDetailDemand]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tblStallDetailDemand] (
    [stallDemandDetailId]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [stallAllocationId]        INT             NOT NULL,
    [demandYear]               INT             NOT NULL,
    [demandDays]               INT             NOT NULL,
    [demandGenerateScheduleId] INT             NOT NULL,
    [demandNoId]               BIGINT          NOT NULL,
    [amount]                   DECIMAL (18, 2) NOT NULL,
    [installmentDate]          DATETIME        NOT NULL,
    [createdBy]                INT             NOT NULL,
    [createdOn]                DATETIME        NOT NULL,
    [modifiedBy]               INT             NULL,
    [modifiedOn]               DATETIME        NULL,
    [stallTypeId]              INT             NOT NULL,
    PRIMARY KEY CLUSTERED ([stallDemandDetailId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tblStallDetailDemand])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblStallDetailDemand] ON;
        INSERT INTO [dbo].[tmp_ms_xx_tblStallDetailDemand] ([stallDemandDetailId], [stallAllocationId], [demandYear], [demandDays], [demandGenerateScheduleId], [demandNoId], [amount], [installmentDate], [createdBy], [createdOn], [modifiedBy], [modifiedOn], [stallTypeId])
        SELECT   [stallDemandDetailId],
                 [stallAllocationId],
                 [demandYear],
                 [demandDays],
                 [demandGenerateScheduleId],
                 [demandNoId],
                 [amount],
                 [installmentDate],
                 [createdBy],
                 [createdOn],
                 [modifiedBy],
                 [modifiedOn],
                 [stallTypeId]
        FROM     [dbo].[tblStallDetailDemand]
        ORDER BY [stallDemandDetailId] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblStallDetailDemand] OFF;
    END

DROP TABLE [dbo].[tblStallDetailDemand];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tblStallDetailDemand]', N'tblStallDetailDemand';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Table [dbo].[mstLandServiceType]...';


GO
CREATE TABLE [dbo].[mstLandServiceType] (
    [landServiceTypeId] INT           IDENTITY (1, 1) NOT NULL,
    [landServiceType]   VARCHAR (150) NOT NULL,
    [isActive]          BIT           NOT NULL,
    [createdBy]         INT           NOT NULL,
    [createdOn]         DATETIME      NOT NULL,
    [modifiedBy]        INT           NULL,
    [modifiedOn]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([landServiceTypeId] ASC)
);


GO
PRINT N'Creating Table [dbo].[trnLandFeeDetail]...';


GO
CREATE TABLE [dbo].[trnLandFeeDetail] (
    [landFeeDetailId]   INT      IDENTITY (1, 1) NOT NULL,
    [landOwnershipId]   INT      NOT NULL,
    [landServiceTypeId] INT      NOT NULL,
    [transactionId]     BIGINT   NOT NULL,
    [createdBy]         INT      NOT NULL,
    [createdOn]         DATETIME NOT NULL,
    [modifiedBy]        INT      NULL,
    [modifiedOn]        DATETIME NULL,
    PRIMARY KEY CLUSTERED ([landFeeDetailId] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblDemand_ToTable_10]...';


GO
ALTER TABLE [dbo].[tblDemand] WITH NOCHECK
    ADD CONSTRAINT [FK_tblDemand_ToTable_10] FOREIGN KEY ([stallDemandDetailId]) REFERENCES [dbo].[tblStallDetailDemand] ([stallDemandDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblLedger_ToTable_5]...';


GO
ALTER TABLE [dbo].[tblLedger] WITH NOCHECK
    ADD CONSTRAINT [FK_tblLedger_ToTable_5] FOREIGN KEY ([stallDemandDetailId]) REFERENCES [dbo].[tblStallDetailDemand] ([stallDemandDetailId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblStallDetailDemand_ToTable_3]...';


GO
ALTER TABLE [dbo].[tblStallDetailDemand] WITH NOCHECK
    ADD CONSTRAINT [FK_tblStallDetailDemand_ToTable_3] FOREIGN KEY ([stallTypeId]) REFERENCES [dbo].[mstStallType] ([stallTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblStallDetailDemand_ToTable]...';


GO
ALTER TABLE [dbo].[tblStallDetailDemand] WITH NOCHECK
    ADD CONSTRAINT [FK_tblStallDetailDemand_ToTable] FOREIGN KEY ([stallAllocationId]) REFERENCES [dbo].[tblStallAllocation] ([stallAllocationId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblStallDetailDemand_ToTable_1]...';


GO
ALTER TABLE [dbo].[tblStallDetailDemand] WITH NOCHECK
    ADD CONSTRAINT [FK_tblStallDetailDemand_ToTable_1] FOREIGN KEY ([demandGenerateScheduleId]) REFERENCES [dbo].[enumDemandGenerateSchedule] ([demandGenerateScheduleId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tblStallDetailDemand_ToTable_2]...';


GO
ALTER TABLE [dbo].[tblStallDetailDemand] WITH NOCHECK
    ADD CONSTRAINT [FK_tblStallDetailDemand_ToTable_2] FOREIGN KEY ([demandNoId]) REFERENCES [dbo].[tblDemandNo] ([demandNoId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnLandFeeDetail_ToTable]...';


GO
ALTER TABLE [dbo].[trnLandFeeDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandFeeDetail_ToTable] FOREIGN KEY ([landOwnershipId]) REFERENCES [dbo].[tblLandOwnershipDetail] ([landOwnershipId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnLandFeeDetail_ToTable_1]...';


GO
ALTER TABLE [dbo].[trnLandFeeDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandFeeDetail_ToTable_1] FOREIGN KEY ([landServiceTypeId]) REFERENCES [dbo].[mstLandServiceType] ([landServiceTypeId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_trnLandFeeDetail_ToTable_2]...';


GO
ALTER TABLE [dbo].[trnLandFeeDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_trnLandFeeDetail_ToTable_2] FOREIGN KEY ([transactionId]) REFERENCES [dbo].[tblTransactionDetail] ([transactionId]);


GO
PRINT N'Refreshing Procedure [dbo].[GetStallDemandScheduleMonthly]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetStallDemandScheduleMonthly]';


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '9398d4c4-002c-4774-b842-9c7168922eaf')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('9398d4c4-002c-4774-b842-9c7168922eaf')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '7222f21d-9518-470e-be38-2469a92cc7ac')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('7222f21d-9518-470e-be38-2469a92cc7ac')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[tblDemand] WITH CHECK CHECK CONSTRAINT [FK_tblDemand_ToTable_10];

ALTER TABLE [dbo].[tblLedger] WITH CHECK CHECK CONSTRAINT [FK_tblLedger_ToTable_5];

ALTER TABLE [dbo].[tblStallDetailDemand] WITH CHECK CHECK CONSTRAINT [FK_tblStallDetailDemand_ToTable_3];

ALTER TABLE [dbo].[tblStallDetailDemand] WITH CHECK CHECK CONSTRAINT [FK_tblStallDetailDemand_ToTable];

ALTER TABLE [dbo].[tblStallDetailDemand] WITH CHECK CHECK CONSTRAINT [FK_tblStallDetailDemand_ToTable_1];

ALTER TABLE [dbo].[tblStallDetailDemand] WITH CHECK CHECK CONSTRAINT [FK_tblStallDetailDemand_ToTable_2];

ALTER TABLE [dbo].[trnLandFeeDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandFeeDetail_ToTable];

ALTER TABLE [dbo].[trnLandFeeDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandFeeDetail_ToTable_1];

ALTER TABLE [dbo].[trnLandFeeDetail] WITH CHECK CHECK CONSTRAINT [FK_trnLandFeeDetail_ToTable_2];


GO
PRINT N'Update complete.';


GO
